# Generated by Django 5.2.14 on 2026-06-01 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('deliverable_type', models.CharField(choices=[('market_study', 'Etude de marche'), ('competitor_study', 'Etude de concurrence'), ('business_plan', 'Business plan'), ('business_strategy', 'Strategie business')], max_length=32)),
                ('gamma_enabled', models.BooleanField(default=False)),
                ('delivery_mode', models.CharField(choices=[('link_and_pdf', 'Lien de telechargement + PDF')], default='link_and_pdf', max_length=32)),
                ('retention_days', models.PositiveSmallIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
