# Generated by Django 5.2.16 on 2026-08-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_weasyprint_moteur_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='prix_unitaire_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
