# Generated by Django 5.2.16 on 2026-08-21 18:15

import catalog.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_offer_prix_unitaire_cents'),
        ('organisations', '0014_mouvementcredit_livrable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitBoutique',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('sommaire', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=80)),
                ('prix_cents', models.PositiveIntegerField(default=0)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('fichier', models.FileField(blank=True, upload_to=catalog.models._chemin_produit)),
                ('fichier_editable', models.FileField(blank=True, upload_to=catalog.models._chemin_produit)),
                ('extrait', models.FileField(blank=True, upload_to=catalog.models._chemin_produit)),
                ('image', models.ImageField(blank=True, upload_to=catalog.models._chemin_produit)),
                ('nombre_de_pages', models.PositiveSmallIntegerField(default=0)),
                ('mise_a_jour_le', models.DateField(blank=True, null=True)),
                ('en_ligne', models.BooleanField(default=False)),
                ('rang', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'produit de boutique',
                'verbose_name_plural': 'produits de boutique',
                'ordering': ['rang', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='AchatProduit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_paiement', models.CharField(max_length=200, unique=True)),
                ('montant_cents', models.PositiveIntegerField(default=0)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telecharge_le', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_boutique', to='organisations.organisation')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='catalog.produitboutique')),
            ],
            options={
                'verbose_name': 'achat de boutique',
                'verbose_name_plural': 'achats de boutique',
                'ordering': ['-created_at'],
            },
        ),
    ]
