# Generated by Django 5.2.16 on 2026-08-21 19:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_produitboutique_achatproduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisProduit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auteur', models.CharField(max_length=120)),
                ('qualite', models.CharField(blank=True, max_length=120)),
                ('note', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('texte', models.TextField(blank=True)),
                ('publie', models.BooleanField(default=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='catalog.produitboutique')),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'ordering': ['-created_at'],
            },
        ),
    ]
