# Generated by Django 5.2.16 on 2026-08-21 19:38

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_avisproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitboutique',
            name='extrait',
            field=models.FileField(blank=True, upload_to=catalog.models._chemin_vitrine),
        ),
        migrations.AlterField(
            model_name='produitboutique',
            name='image',
            field=models.ImageField(blank=True, upload_to=catalog.models._chemin_vitrine),
        ),
    ]
