# Generated by Django 5.2.16 on 2026-08-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_produitboutique_extrait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatproduit',
            name='avis_demande_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avisproduit',
            name='achat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to='catalog.achatproduit'),
        ),
    ]
