# Generated by Django 5.2.16 on 2026-08-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_achatproduit_avis_demande_le_avisproduit_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitboutique',
            name='extrait',
        ),
        migrations.AddField(
            model_name='produitboutique',
            name='apercu_actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produitboutique',
            name='apercu_pages',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
