# Generated by Django 5.2.14 on 2026-06-01 01:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deliverable_type', models.CharField(choices=[('market_study', 'Etude de marche'), ('competitor_study', 'Etude de concurrence'), ('business_plan', 'Business plan'), ('business_strategy', 'Strategie business')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Termine'), ('failed', 'Echec'), ('cancelled', 'Annule')], default='pending', max_length=16)),
                ('budget_eur', models.DecimalField(decimal_places=4, default=Decimal('2.0000'), max_digits=8)),
                ('total_cost_eur', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('context_summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generation_job', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterGeneration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.PositiveSmallIntegerField()),
                ('chapter_title', models.CharField(max_length=220)),
                ('prompt_key', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Termine'), ('failed', 'Echec'), ('skipped', 'Ignore')], default='pending', max_length=16)),
                ('content', models.TextField(blank=True)),
                ('operational_summary', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_eur', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='generation.generationjob')),
            ],
            options={
                'ordering': ['job', 'chapter_number'],
                'constraints': [models.UniqueConstraint(fields=('job', 'chapter_number'), name='uniq_chapter_generation_per_job')],
            },
        ),
    ]
