# Generated by Django 5.2.14 on 2026-06-01 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoherenceFact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('market_size', 'Taille de marche'), ('growth_rate', 'Taux de croissance'), ('currency', 'Devise'), ('assumption', 'Hypothese'), ('source', 'Source')], max_length=32)),
                ('key', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=500)),
                ('source_chapter_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coherence_facts', to='generation.generationjob')),
            ],
            options={
                'ordering': ['job', 'kind', 'key'],
                'constraints': [models.UniqueConstraint(fields=('job', 'kind', 'key'), name='uniq_coherence_fact_per_job_kind_key')],
            },
        ),
    ]
