# Generated by Django 5.2.14 on 2026-06-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_coherencefact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coherencefact',
            name='kind',
            field=models.CharField(choices=[('market_size', 'Taille de marche'), ('growth_rate', 'Taux de croissance'), ('currency', 'Devise'), ('assumption', 'Hypothese'), ('source', 'Source'), ('competitor', 'Concurrent')], max_length=32),
        ),
    ]
