# Generated by Django 5.2.14 on 2026-07-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0008_generationjob_phase0_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='coherencefact',
            name='provenance',
            field=models.CharField(choices=[('client', 'Brief client'), ('generated', 'Extrait de la génération')], default='generated', help_text='Origine du fait : brief client (intangible, priorite absolue) ou extraction du contenu genere (repere de coherence).', max_length=16),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='qa_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('passed', 'Validé'), ('failed', 'Echec partiel'), ('blocked', 'Bloqué par le gate qualité')], default='pending', help_text='Statut de la passe QA post-génération (correction automatique des chapitres).', max_length=16),
        ),
    ]
