# Generated by Django 5.2.14 on 2026-07-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0009_coherencefact_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='research_brief',
            field=models.TextField(blank=True),
        ),
    ]
