# Generated by Django 5.2.16 on 2026-07-29 10:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0010_generationjob_research_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocleDonnees',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='Incrémentée à chaque régénération explicite du socle.')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('invalide', 'Invalidé')], default='brouillon', max_length=16)),
                ('contenu', models.JSONField(blank=True, default=dict, help_text="Socle sérialisé, conforme à generation/socle/schema.py. Modifiable ici : c'est le point de correction manuelle avant que l'étude ne se construise sur ces chiffres.")),
                ('motifs_rejet', models.JSONField(blank=True, default=list, help_text='Motifs du dernier refus de validation. Vide si le socle est valide.')),
                ('tentatives', models.PositiveSmallIntegerField(default=0, help_text="Nombre d'appels au modèle consommés pour produire ce socle.")),
                ('corrige_manuellement', models.BooleanField(default=False, help_text='Vrai si un humain a modifié le contenu après la génération.')),
                ('valide_at', models.DateTimeField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_eur', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socle', to='generation.generationjob')),
            ],
            options={
                'verbose_name': 'Socle de données',
                'verbose_name_plural': 'Socles de données',
                'ordering': ['-created_at'],
            },
        ),
    ]
