# Generated by Django 5.2.16 on 2026-07-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0011_socledonnees'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptergeneration',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Termine'), ('failed', 'Echec'), ('cancelled', 'Annule'), ('intervention_requise', 'Intervention requise')], default='pending', max_length=24),
        ),
    ]
