# Generated by Django 5.2.16 on 2026-08-09 05:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0013_backfill_str_conclusion_prompt_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptergeneration',
            name='cache_read_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chaptergeneration',
            name='cache_write_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chaptergeneration',
            name='cost_perdu_eur',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
    ]
