# Generated by Django 5.2.16 on 2026-09-11 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0014_compteurs_de_cache_et_tentatives_perdues'),
        ('organisations', '0017_jetonacces_assistance_jetonacces_ouvert_par_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentClientLu',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('nom', models.CharField(max_length=200)),
                ('depose_le', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('lu', 'Lu en entier'), ('tronque', 'Lu en partie'), ('illisible', 'Illisible'), ('non_lu', 'Format non lu')], max_length=12)),
                ('caracteres_extraits', models.PositiveIntegerField(default=0)),
                ('caracteres_retenus', models.PositiveIntegerField(default=0)),
                ('motif', models.CharField(blank=True, max_length=300)),
                ('texte', models.TextField(blank=True)),
                ('texte_efface_le', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_client', to='generation.generationjob')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisations.piecejointe')),
            ],
            options={
                'ordering': ['job', 'ordre'],
            },
        ),
    ]
