# Generated by Django 5.2.16 on 2026-09-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0015_documents_client_lus'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='controle_final',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
