# Generated by Django 5.2.16 on 2026-09-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0016_trace_du_controle_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coherencefact',
            name='value',
            field=models.TextField(),
        ),
    ]
