# Generated by Django 5.2.16 on 2026-09-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0017_valeur_de_fait_sans_troncature'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='memoire_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='memoire_etude',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
