# Generated by Django 5.2.16 on 2026-09-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0018_memoire_de_l_etude'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptergeneration',
            name='etape',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
