# Generated by Django 5.2.14 on 2026-06-01 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systeme_order_id', models.CharField(max_length=140, unique=True)),
                ('status', models.CharField(choices=[('received', 'Recue'), ('waiting_intake', 'En attente formulaire'), ('processing', 'En traitement'), ('delivered', 'Livree'), ('failed', 'Echec'), ('cancelled', 'Annulee')], default='received', max_length=32)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.offer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
