# Generated by Django 5.2.16 on 2026-07-29 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_period_year_month'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='organisations.organisation'),
        ),
    ]
