# Generated by Django 5.2.14 on 2026-06-01 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('tally', 'Tally'), ('typeform', 'Typeform'), ('manual', 'Manuel')], default='tally', max_length=16)),
                ('status', models.CharField(choices=[('received', 'Recue'), ('incomplete', 'Incomplete'), ('normalized', 'Normalisee'), ('rejected', 'Rejetee')], default='received', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_variables', models.JSONField(blank=True, default=dict)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_submission', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
