# Generated by Django 5.2.14 on 2026-06-01 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyee'), ('failed', 'Echec')], default='pending', max_length=16)),
                ('email_provider', models.CharField(choices=[('brevo', 'Brevo')], default='brevo', max_length=16)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('download_url', models.URLField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('artifacts', models.ManyToManyField(blank=True, related_name='delivery_batches', to='documents.documentartifact')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_batches', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyee'), ('failed', 'Echec')], max_length=16)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('provider_message_id', models.CharField(blank=True, max_length=160)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='delivery.deliverybatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
