from __future__ import annotations

from .reference_em import REFERENCE_SOM

# Bibliotheque d'instructions par chapitre (remplace le "parsing" des prompts
# proprietaires EVKHA). Source de verite : "PROMPT FINAL VERSION 3 EM_EC" +
# "Consignes d'ecriture EVKHA". Texte reformule, fidele a la methode, sans
# marqueurs internes (jamais "Etape", "Verification", "Prompt a utiliser"
# dans la sortie attendue). Les variables [SECTEUR]/[PAYS]/[ZONE]/[PROJET]
# sont injectees via le contexte, pas en dur ici.

# --- Etude de marche (EM) -------------------------------------------------

MARKET_STUDY_PROMPTS: dict[str, str] = {
    "em.00.fiche_projet": (
        "FICHE PROJET — carte d'identite de l'etude (manuel §2, p. 3).\n"
        "Objectif : reformuler le brief Tally et les pieces jointes en une "
        "fiche claire, qui reste presente pendant toute la production et est "
        "enrichie apres chaque CHECK.\n"
        "\n"
        "FORMAT STRICT : produis EXACTEMENT un tableau Markdown a 2 colonnes, "
        "aucun texte autour, aucune introduction, aucun commentaire. Rubriques "
        "obligatoires dans cet ordre (manuel §2) :\n"
        "| Rubrique | Contenu |\n"
        "|---|---|\n"
        "| Projet | Nom, activite envisagee, offre, stade d'avancement et "
        "objectif du porteur. |\n"
        "| Marche exact | Secteur principal, sous-secteur, produits ou "
        "services reellement concernes. |\n"
        "| Geographie | Pays, ville ou zone d'implantation, puis continent "
        "pertinent. Jamais l'Europe par defaut. |\n"
        "| Clientele | B2C, B2B, institutions, cibles deja envisagees, "
        "profil et besoins. |\n"
        "| Positionnement | Niveau de gamme, proposition de valeur, "
        "particularites, differenciation envisagee. |\n"
        "| Modele | Mode de vente, canaux, frequence, revenus attendus et "
        "capacites connues. |\n"
        "| Demandes explicites | Toutes les questions et attentes ecrites par "
        "le client, sans en oublier une. |\n"
        "| Questions implicites | Ce qu'un porteur de projet dans ce domaine "
        "doit normalement comprendre avant de se lancer. |\n"
        "| Contraintes | Budget, delai, reglementation pressentie, ressources, "
        "limites, points sensibles. |\n"
        "| Identite visuelle | Logo fourni, couleurs EVKHA, consignes de "
        "marque et format final. |\n"
        "\n"
        "Apres le tableau, saute une ligne et ajoute UNE seule section "
        "intitulee « ## Questions auxquelles cette etude repond » avec une "
        "liste a puces de 4 a 5 questions du porteur (explicites + implicites). "
        "Rien d'autre. Aucune phrase meta du type « Voici la fiche projet »."
    ),
    "em.01.marche_mondial_europeen": (
        "CHAPITRE 1 — Marche mondial et continent pertinent (manuel §6, p. 8).\n"
        "Objectif : etablir la taille, la croissance, les dynamiques et les "
        "perspectives du marche a l'echelle mondiale puis dans le continent "
        "reellement pertinent pour le projet.\n"
        "Contenu obligatoire :\n"
        "- Definition exacte du marche et de son perimetre.\n"
        "- Valeurs observees recentes, historique utile et TCAC calcule ou "
        "verifie.\n"
        "- Repartition geographique, zones dominantes et moteurs de croissance.\n"
        "- Projection prudente a 2030 avec hypotheses.\n"
        "Visuel utile : courbe historique et projection, monde versus continent "
        "pertinent."
    ),
    # Chapitre volontairement NON decoupe en sections, contrairement au
    # chapitre 1. Le decoupage « 2.a national / 2.b local » a produit sur le
    # run reel 010e3bf2 deux jeux de chiffres pour le meme marche accessible
    # (SAM regional a 240 kEUR dans une section, 250 kEUR dans l'autre) : la
    # section b ne voyait de la section a qu'un resume de 1200 caracteres, donc
    # elle recalculait. Or l'emboitement TAM > SAM > SOM est UN raisonnement
    # arithmetique continu : le couper en deux appels, c'est demander deux fois
    # le meme calcul et esperer la meme reponse. Un seul appel, un seul calcul.
    "em.02.marche_national_local": (
        "CHAPITRE 2 — Marche national, local et marche accessible (manuel §6, p. 8).\n"
        "Objectif : mesurer le terrain reel d'implantation et transformer la "
        "vue macro en potentiel accessible. Le pays cible est extrait de "
        "VARIABLES_PROJET.PAYS, la zone de VARIABLES_PROJET.ZONE.\n"
        "Contenu obligatoire, dans cet ordre :\n"
        "1. Marche NATIONAL : taille et dynamique (valeur, volume, TCAC "
        "national), acteurs structurants sans benchmark concurrentiel "
        "detaille, maturite et structure (concentration, distribution), "
        "specificites nationales utiles (reglementation, habitudes de "
        "consommation), projection nationale lorsque defendable.\n"
        "2. Marche LOCAL sur la zone cible : demographie, revenus, emploi, "
        "flux, usages, densite et demande ; projection locale lorsque "
        "defendable, avec estimation argumentee si les donnees directes "
        "manquent.\n"
        "3. Marche ACCESSIBLE : TAM top-down, SAM filtre par zone/cible/offre, "
        "SOM bottom-up annee 1 ET annee 3.\n"
        "Ne repete pas les chiffres mondiaux et continentaux du chapitre 1 : "
        "tu les reprends comme point de depart, tu ne les re-estimes pas.\n"
        "\n"
        "DISTINCTION CRITIQUE mondial / continental (erreur fatale de coherence) :\n"
        "Le bloc CHIFFRES_FONDATIONS contient DEUX valeurs separees et differentes :\n"
        "  - `taille_marche_mondial` = taille totale du marche mondial (toutes "
        "geographies, toutes technologies pertinentes au projet)\n"
        "  - `taille_marche_continental` = part de ce marche a l'echelle du "
        "continent pertinent (ex. Europe IA strict pour un projet francais)\n"
        "Ces deux valeurs sont differentes. Si tu ouvres ce chapitre avec une "
        "phrase du type 'Le chapitre 1 a etabli que le marche mondial represente X', "
        "X doit etre EXACTEMENT `taille_marche_mondial`, jamais `taille_marche_continental`. "
        "Confondre les deux dans la phrase d'ouverture propage l'erreur dans tous "
        "les chapitres suivants qui s'appuient sur ce chapitre comme reference.\n"
        "\n"
        "REGLES DE CALCUL DU MARCHE ACCESSIBLE (non negociables) :\n"
        "- Ecris le calcul, pas seulement le resultat. Chaque etape nomme ses "
        "variables et leur valeur : population de la zone, taux de "
        "penetration retenu, panier ou ticket moyen, frequence annuelle, "
        "part de capture visee. Un lecteur doit pouvoir refaire le calcul et "
        "retrouver ton chiffre.\n"
        "- Un seul TAM, un seul SAM, un seul SOM par annee. Si tu donnes une "
        "fourchette, elle sert partout ensuite a l'identique.\n"
        "- L'emboitement TAM > SAM > SOM doit etre vrai en euros compares. "
        "Verifie-le avant d'ecrire : convertis tout dans la meme unite.\n"
        "- Le SOM annee 1 depasse rarement quelques pour cent du SAM. "
        "Si ton calcul donne davantage, c'est que le SAM est sous-estime ou "
        "que le SOM est irrealiste : refais le calcul. Ne justifie JAMAIS un "
        "taux de capture eleve par un argument redactionnel.\n"
        "- Ces trois valeurs sont reutilisees telles quelles aux chapitres 14 "
        "et 15 (manuel p. 6). Elles doivent etre justes ici, elles ne seront "
        "plus recalculees.\n"
        # Consigne redigee pour rester vraie que l'outil d'execution de code
        # soit cable ou non (cf. EVKHA_CODE_EXECUTION_ENABLED). La seconde
        # phrase est la protection qui compte : les blocs d'outil sont deja
        # filtres du livrable par integrations/claude.py, mais rien n'empeche le
        # modele d'ECRIRE « j'ai execute un script pour verifier » — et cette
        # phrase, elle, atterrirait dans le chapitre livre au client.
        "- Quand un outil d'execution de code est a ta disposition, pose ces "
        "calculs dedans au lieu de les faire de tete : l'emboitement "
        "TAM > SAM > SOM, les conversions d'unites et la montee en charge "
        "mensuelle sont des enchainements ou une erreur d'arrondi se propage "
        "jusqu'aux chapitres 14 et 15.\n"
        "- Le livrable montre le calcul en langage METIER : variables, valeurs, "
        "formule, hypotheses et sources, comme l'exige la colonne « Formule et "
        "sources » du manuel p. 6. Il ne montre RIEN de la technique : ni code, "
        "ni sortie de console, ni mention d'un script, d'un outil, d'un calcul "
        "« verifie » ou d'une procedure. Tu ecris pour un porteur de projet et "
        "son banquier, pas un journal de travail.\n"
        + REFERENCE_SOM +
        "\n"
        "DERIVATION SAM vers SOM — paragraphe obligatoire (c'est ce que le CHECK 1 "
        "verifie en priorite) :\n"
        "Immediatement apres avoir annonce le SOM An1, insere un paragraphe intitule "
        "en gras '**Formule et derivation SOM depuis le SAM**' contenant :\n"
        "1. La formule litterale : SOM = SAM × taux de capture\n"
        "2. Les valeurs numeriques completees : SOM An1 = [SAM en euros] × [taux]% "
        "= [SOM en euros]\n"
        "3. La justification du taux de capture retenu (une phrase)\n"
        "4. La meme derivation pour le SOM An3\n"
        "5. La verification de l'emboitement : TAM > SAM > SOM An3 > SOM An1 "
        "en euros sur une seule ligne\n"
        "Ce paragraphe est non-negociable : sans lui, le chapitre est rejete par "
        "le CHECK 1 (bloc A — Fondations du marche).\n"
        "\n"
        "Visuel utile (manuel) : graphique national/local + schema TAM/SAM/SOM. "
        "En fin de chapitre, genere UN graphique HTML en barres montrant la "
        "repartition ou la dynamique du marche local par segment, en "
        "utilisant ce pattern exact (adapte valeurs et etiquettes au "
        "contexte reel) :\n"
        "<h3 style=\"font-size:13pt;margin:4mm 0 2mm\">Repartition du marche local — segments cles</h3>\n"  # noqa: E501
        "<table style=\"border-collapse:collapse;width:100%;margin:3mm 0;font-size:9pt\">\n"
        "<tr><td style=\"padding:1.5mm 3mm;border-bottom:0.5pt solid #EFEAD8;width:30%\">Segment A</td>"  # noqa: E501
        "<td style=\"padding:1.5mm 2mm;width:60%\">"
        "<div style=\"background:#C9A227;height:5mm;width:72%;display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold;width:10%\">XX %</td></tr>\n"
        "<tr><td style=\"padding:1.5mm 3mm;border-bottom:0.5pt solid #EFEAD8\">Segment B</td>"
        "<td style=\"padding:1.5mm 2mm\">"
        "<div style=\"background:#C9A227;height:5mm;width:50%;display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold\">XX %</td></tr>\n"
        "<tr><td style=\"padding:1.5mm 3mm\">Segment C</td>"
        "<td style=\"padding:1.5mm 2mm\">"
        "<div style=\"background:#1A1A1A;height:5mm;width:28%;display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold\">XX %</td></tr>\n"
        "</table>\n"
        "<p style=\"font-style:italic;font-size:8.5pt;color:#5A5A5A\">"
        "Source : [cite ta source]. Estimations argumentees sur la base des donnees disponibles.</p>\n"  # noqa: E501
        "Remplace Segment A/B/C et XX par les vraies donnees etablies dans l'analyse."
    ),
    "em.03.segmentation": (
        "CHAPITRE 3 — Segmentation approfondie (manuel §6, p. 9).\n"
        "Objectif : identifier les groupes, zones et comportements qui "
        "structurent le marche et prioriser les segments compatibles avec le "
        "projet.\n"
        "Contenu obligatoire :\n"
        "- Segmentation geographique, demographique, psychographique et "
        "comportementale.\n"
        "- Segmentation par usage, frequence, solvabilite, niveau de gamme et "
        "maturite digitale.\n"
        "- Axes B2B/B2C, prescripteurs, partenaires ou institutions lorsqu'ils "
        "sont pertinents.\n"
        "- Poids ou ordre de grandeur des segments lorsque defendable.\n"
        "Visuel utile : carte ou matrice de segmentation, limitee aux axes utiles."
    ),
    "em.04.avantages_inconvenients": (
        "CHAPITRE 4 — Avantages et contraintes structurelles du secteur "
        "(manuel §6, p. 10).\n"
        "Objectif : presenter les facteurs favorables deja installes et les "
        "contraintes durables du secteur.\n"
        "Contenu obligatoire :\n"
        "- Au moins 5 avantages structurants et 5 contraintes reellement "
        "distinctes.\n"
        "- Donnees, exemples ou faits observables pour chaque point important.\n"
        "- Impact sur l'entree, les couts, la demande, la marge, la confiance "
        "ou les operations.\n"
        "- Effet specifique sur le projet.\n"
        "Visuel obligatoire : en fin de chapitre, genere un tableau HTML comparatif "
        "avantages / contraintes. Format exact (remplace les exemples par les vrais "
        "points du projet) :\n"
        "<h3 style=\"font-size:13pt;margin:4mm 0 2mm\">Balance avantages / contraintes</h3>\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:3mm 0;font-size:9pt\">\n"
        "<thead><tr>"
        "<th style=\"background:#2E7D4F;color:#fff;padding:2mm 4mm;width:50%;text-align:left\">Avantages structurants</th>"
        "<th style=\"background:#B73E3E;color:#fff;padding:2mm 4mm;width:50%;text-align:left\">Contraintes durables</th>"
        "</tr></thead><tbody><tr><td style=\"vertical-align:top;padding:3mm 4mm;border:0.5pt solid #EFEAD8\">"
        "<ul style=\"margin:0;padding-left:4mm\">"
        "<li>Avantage 1 (ref. au texte)</li>"
        "<li>Avantage 2</li>"
        "<li>Avantage 3</li>"
        "<li>Avantage 4</li>"
        "<li>Avantage 5</li>"
        "</ul></td>"
        "<td style=\"vertical-align:top;padding:3mm 4mm;border:0.5pt solid #EFEAD8\">"
        "<ul style=\"margin:0;padding-left:4mm\">"
        "<li>Contrainte 1 (ref. au texte)</li>"
        "<li>Contrainte 2</li>"
        "<li>Contrainte 3</li>"
        "<li>Contrainte 4</li>"
        "<li>Contrainte 5</li>"
        "</ul></td></tr></tbody></table>\n"
        "Remplace chaque item par les vrais avantages et contraintes identifies dans l'analyse. "
        "Ce tableau est obligatoire — sans lui le visuel manquant invalide le chapitre."
    ),
    "em.05.defis_opportunites": (
        "CHAPITRE 5 — Defis et opportunites 2026-2030 (manuel §6, p. 10).\n"
        "Objectif : identifier les transformations a venir qui peuvent creer de "
        "la valeur ou fragiliser le projet.\n"
        "Contenu obligatoire :\n"
        "- Au moins 5 defis et 5 opportunites distincts.\n"
        "- Horizon, probabilite, intensite et mecanisme d'impact.\n"
        "- Signaux faibles ou changements emergents etayes.\n"
        "- Leviers activables par le projet et points de vigilance.\n"
        "Visuel obligatoire : en fin d'analyse (apres les 5 defis et 5 opportunites), "
        "genere UNE matrice HTML impact/horizon. Format exact :\n"
        "<h3 style=\"font-size:13pt;margin:4mm 0 2mm\">Matrice impact / horizon — defis et opportunites</h3>\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:3mm 0;font-size:9pt\">\n"
        "<thead><tr>"
        "<th style=\"background:#1A1A1A;color:#fff;padding:2mm 3mm;width:40%\">Item</th>"
        "<th style=\"background:#1A1A1A;color:#fff;padding:2mm 3mm;text-align:center;width:15%\">Type</th>"
        "<th style=\"background:#1A1A1A;color:#fff;padding:2mm 3mm;text-align:center;width:20%\">Horizon</th>"
        "<th style=\"background:#1A1A1A;color:#fff;padding:2mm 3mm;text-align:center;width:25%\">Intensite d'impact</th>"
        "</tr></thead><tbody>\n"
        "<tr><td style=\"padding:2mm 3mm;border:0.5pt solid #EFEAD8\">Defi 1 — [libelle court]</td>"
        "<td style=\"padding:2mm 3mm;text-align:center;border:0.5pt solid #EFEAD8;color:#B73E3E;font-weight:bold\">DEFI</td>"
        "<td style=\"padding:2mm 3mm;text-align:center;border:0.5pt solid #EFEAD8\">2026-2027</td>"
        "<td style=\"padding:2mm 3mm;text-align:center;border:0.5pt solid #EFEAD8;background:#B73E3E;color:#fff\">Fort</td></tr>\n"
        "</tbody></table>\n"
        "<p style=\"font-style:italic;font-size:8.5pt;color:#5A5A5A\">DEFI = contrainte externe ; "
        "OPPORT. = levier d'action. Intensite : Fort / Modere / Faible.</p>\n"
        "Inclus les 10 items (5 defis + 5 opportunites) dans ce tableau, dans l'ordre "
        "decroissant d'intensite. Ce tableau est obligatoire — NE PAS ecrire "
        "'le tableau ci-dessous' sans le generer immediatement apres."
    ),
    "em.06.reglementation": (
        "CHAPITRE 6 — Reglementation, normes et conformite (manuel §6, p. 11).\n"
        "Objectif : traduire les obligations applicables en consequences "
        "concretes pour le lancement et l'exploitation.\n"
        "Contenu obligatoire :\n"
        "- Textes, licences, agrements, statuts, obligations fiscales, "
        "douanieres ou environnementales pertinents.\n"
        "- Distinction obligatoire/recommande et national/international.\n"
        "- Organisme competent et date de verification.\n"
        "- Cout, delai, sequence ou risque de non-conformite lorsque documente.\n"
        "Visuel utile : parcours de conformite ou tableau obligations/actions.\n"
        "Rappel : aucune affirmation ne remplace l'avis d'un professionnel du "
        "droit, de la fiscalite ou de la conformite."
    ),
    "em.07.tendances_court_terme": (
        "CHAPITRE 7 — Tendances a court terme 2026-2027 (manuel §6, p. 12).\n"
        "Objectif : presenter les evolutions actuelles susceptibles de modifier "
        "rapidement la demande, les usages ou l'offre.\n"
        "Contenu obligatoire :\n"
        "- Au moins 5 tendances distinctes et recentes.\n"
        "- Preuve observable, date et niveau de maturite.\n"
        "- Effet attendu sur la cible, les prix, les canaux ou le produit.\n"
        "- Distinction tendance structurelle/effet de mode.\n"
        "Visuel utile : frise 2026-2027 ou radar de tendances."
    ),
    "em.08.perspectives_long_terme": (
        "CHAPITRE 8 — Perspectives et scenarios a horizon 2030 (manuel §6, p. 12).\n"
        "Objectif : construire une vision long terme prudente et utile a la "
        "perennite du projet.\n"
        "Contenu obligatoire :\n"
        "- Mutations technologiques, societales, economiques, environnementales "
        "et reglementaires pertinentes.\n"
        "- Scenarios prudent, central et dynamique lorsque la sensibilite est "
        "forte.\n"
        "- Hypotheses et signaux soutenant chaque scenario.\n"
        "- Risques structurels et leviers durables.\n"
        "Visuel utile : frise ou tableau de scenarios a 2030.\n"
        "Rappel : perspectives presentees comme projections ou scenarios, jamais "
        "comme certitudes.\n"
        "CONTRAINTE ABSOLUE — coherence chiffres-fondations : toutes les tailles "
        "de marche (TAM mondial, continental, national) et tous les TCAC que tu "
        "mentionnes dans ce chapitre DOIVENT etre exactement ceux du bloc "
        "CHIFFRES_FONDATIONS de ton contexte. Ne recalcule pas, ne re-derive pas, "
        "ne cite pas de chiffre de memoire. Si un scenario chiffre s'ecarte "
        "d'une valeur fondation, exprime l'ecart en % relatif a la valeur fondation.\n"
        "Distinction critique : `taille_marche_mondial` et `taille_marche_continental` "
        "sont deux valeurs DIFFERENTES dans CHIFFRES_FONDATIONS. La valeur continentale "
        "n'est jamais le marche mondial — labellise chaque chiffre avec son perimetre exact."
    ),
    "em.09.douze_chiffres_cles": (
        "CHAPITRE 9 — Les 12 chiffres cles (manuel §6, p. 13).\n"
        "Objectif : selectionner les donnees les plus fortes et reutilisables "
        "pour comprendre le marche en quelques minutes.\n"
        "Contenu obligatoire :\n"
        "- Exactement 12 chiffres issus du registre valide (fiche projet "
        "enrichie et chapitres precedents).\n"
        "- Diversite : taille, croissance, comportements, frequence, prix, "
        "digital, environnement ou reglementation.\n"
        "- Une explication courte et une consequence pour chaque chiffre.\n"
        "- Annee, zone, unite et statut observe/estime/projete.\n"
        "Visuel utile : tuiles chiffrees ou tableau synthetique lisible "
        "(manuel §6, p. 13). Les 12 chiffres doivent tous apparaitre dans "
        "le chapitre — aucun n'est a supprimer pour un visuel.\n"
        "CONTRAINTE ABSOLUE — coherence chiffres-fondations : pour chaque chiffre "
        "faisant reference a la taille du marche (TAM mondial, continental, "
        "national) ou a un TCAC, tu DOIS utiliser EXACTEMENT la valeur presente "
        "dans le bloc CHIFFRES_FONDATIONS de ton contexte. Interdiction formelle "
        "de citer un chiffre de marche different de ceux du bloc CHIFFRES_FONDATIONS. "
        "Distinction critique : `taille_marche_mondial` et `taille_marche_continental` "
        "sont deux valeurs DIFFERENTES — ne confonds pas les deux dans les tuiles. "
        "Pour le premier chiffre cle (taille du marche), verifie que le libelle "
        "de zone ('Mondial', 'Europe', 'France'...) correspond exactement au "
        "perimetre reel de la valeur dans CHIFFRES_FONDATIONS. "
        "Si CHIFFRES_FONDATIONS contient 'taille_marche_continental = 1,1 Md EUR "
        "(2024)', alors ton chiffre cle doit afficher exactement '1,1 Md EUR (2024)', "
        "pas '900 M EUR', pas '1,2 Md EUR', pas aucune autre valeur."
    ),
    "em.10.clientele_cible": (
        "CHAPITRE 10 — Clientele cible et comportements d'achat (manuel §6, p. 13).\n"
        "Objectif : comprendre ce que les clients recherchent, achetent, paient, "
        "refusent et utilisent.\n"
        "Contenu obligatoire :\n"
        "- Produits ou prestations les plus recherches.\n"
        "- Frequence d'achat ou d'usage, cycle de decision et saisonnalite.\n"
        "- Prix actuellement payes, fourchettes acceptables et sensibilite au "
        "prix lorsque pertinent.\n"
        "- Motivations, freins, criteres de confiance, canaux et role des avis.\n"
        "Visuel utile : parcours de decision ou matrice attentes/freins/leviers."
    ),
    "em.11.personas": (
        "CHAPITRE 11 — Deux personas fondes sur les donnees (manuel §6, p. 13).\n"
        "Objectif : transformer les deux cibles les plus utiles en profils "
        "operationnels pour l'offre et la communication.\n"
        "Contenu obligatoire :\n"
        "- Persona 1 correspondant a la cible principale ; persona 2 reellement "
        "complementaire. EXACTEMENT deux personas, ni plus, ni moins.\n"
        "- Contexte, objectifs, frequence, budget, criteres, canaux, freins et "
        "declencheurs.\n"
        "- Elements relies aux chapitres 3 (segmentation) et 10 (clientele).\n"
        "- Leviers de conversion et adaptations de l'offre.\n"
        "Visuel utile : deux fiches persona sobres et comparables.\n"
        "\n"
        "STRUCTURE — sous-titres uniques : chaque persona a son propre bloc, "
        "chaque sous-titre est PREFIXE par le prenom du persona.\n"
        "## Persona 1 — [Prenom]\n"
        "### [Prenom] — Contexte\n"
        "### [Prenom] — Motivations et declencheurs\n"
        "### [Prenom] — Freins et objections\n"
        "### [Prenom] — Parcours d'achat et canaux\n"
        "## Persona 2 — [Prenom2]\n"
        "### [Prenom2] — Contexte\n"
        "(idem pour les autres sous-titres)."
    ),
    "em.12.risques_plan_gestion": (
        "CHAPITRE 12 — Risques et plan de maitrise (manuel §6, p. 14).\n"
        "Objectif : identifier les vulnerabilites du marche et du projet, puis "
        "proposer des mesures concretes.\n"
        "Contenu obligatoire :\n"
        "- Risques marche, reglementaires, commerciaux, financiers, "
        "operationnels, technologiques et reputationnels.\n"
        "- Cause, probabilite, impact, horizon et signal d'alerte.\n"
        "- Mesure preventive, action corrective et responsable recommande.\n"
        "- Risque residuel apres action.\n"
        "Visuel utile : registre des risques synthetique."
    ),
    "em.13.cartographie_risques": (
        "CHAPITRE 13 — Cartographie des risques externes (manuel §6, p. 14).\n"
        "Objectif : hierarchiser visuellement les risques externes selon leur "
        "probabilite et leur impact.\n"
        "Contenu obligatoire :\n"
        "- 5 a 8 risques externes maximum, issus du chapitre 12.\n"
        "- Matrice 3 x 3 avec definitions explicites des axes.\n"
        "- Placement coherent avec les scores du registre.\n"
        "- Legende courte et lecture des priorites.\n"
        "Visuel utile : matrice probabilite/impact haute resolution.\n"
        "\n"
        "Introduction : 2 a 3 paragraphes d'analyse contextuelle des risques "
        "macro-environnementaux. Puis genere UNE SEULE matrice HTML inline "
        "(sans balises <html>/<body>). Format exact — remplace les exemples "
        "par les vrais risques du projet :\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:4mm 0;font-size:9.5pt\">\n"
        "<thead><tr>"
        "<th style=\"background:#1A1A1A;color:#fff;padding:2mm 3mm;text-align:left\">Risque</th>"
        "<th style=\"background:#1A1A1A;color:#fff;padding:2mm 3mm;text-align:center\">Probabilite</th>"  # noqa: E501
        "<th style=\"background:#1A1A1A;color:#fff;padding:2mm 3mm;text-align:center\">Impact</th>"
        "<th style=\"background:#1A1A1A;color:#fff;padding:2mm 3mm;text-align:center\">Niveau</th>"
        "<th style=\"background:#1A1A1A;color:#fff;padding:2mm 3mm;text-align:left\">Mitigation</th>"  # noqa: E501
        "</tr></thead>\n"
        "<tbody>\n"
        "<tr><td style=\"padding:2mm 3mm;border:0.5pt solid #EFEAD8\">Risque exemple 1</td>"
        "<td style=\"padding:2mm 3mm;text-align:center;border:0.5pt solid #EFEAD8\">Elevee</td>"
        "<td style=\"padding:2mm 3mm;text-align:center;border:0.5pt solid #EFEAD8\">Fort</td>"
        "<td style=\"padding:2mm 3mm;text-align:center;background:#B73E3E;color:#fff;border:0.5pt solid #EFEAD8\">CRITIQUE</td>"  # noqa: E501
        "<td style=\"padding:2mm 3mm;border:0.5pt solid #EFEAD8\">Action corrective</td></tr>\n"
        "<tr><td colspan=\"5\" style=\"background:#FBF8EF;padding:1mm\"></td></tr>\n"
        "</tbody></table>\n"
        "Niveaux de couleur : CRITIQUE = background:#B73E3E / ELEVE = background:#E65100 / "
        "MODERE = background:#C9A227 / FAIBLE = background:#2E7D4F. Tous en color:#fff. "
        "Identifie 5 a 8 risques reels propres au secteur et a la zone, "
        "issus du chapitre 12 (manuel §6, p. 14 : 5-8 maximum). "
        "Termine par une legende courte sous le tableau expliquant la lecture des priorites."
    ),
    "em.14.rentabilite_viabilite": (
        "CHAPITRE 14 — Potentiel de viabilite (manuel §6, p. 14).\n"
        "Objectif : evaluer si le projet peut etre durable au regard du marche, "
        "sans remplacer le previsionnel financier.\n"
        "Contenu obligatoire :\n"
        "- Adequation besoin/offre, accessibilite de la cible et capacite de "
        "differenciation.\n"
        "- Compatibilite entre SOM, ressources, cycle de vente et modele "
        "economique.\n"
        "- Facteurs de resilience et dependances critiques.\n"
        "- Seuils ou conditions de vigilance lorsque defendables.\n"
        "Visuel utile : scorecard de viabilite avec justification, jamais un "
        "score decoratif.\n"
        "Rappel : aucun previsionnel financier ou resultat de rentabilite ne "
        "doit etre invente ; ce chapitre ne remplace pas un business plan."
    ),
    "em.15.graphiques_tableaux": (
        "CHAPITRE 15 — Tableau de bord visuel du marche (manuel §6, p. 15).\n"
        "Objectif : consolider les visuels les plus utiles sans creer de "
        "nouvelles donnees.\n"
        "Contenu obligatoire :\n"
        "- 3 a 5 visuels maximum selectionnes selon le projet.\n"
        "- Evolution du marche, TAM/SAM/SOM, cible, risque ou geographie selon "
        "pertinence.\n"
        "- Donnees appelees directement depuis la fiche projet enrichie et les "
        "chapitres precedents. Aucune nouvelle valeur introduite.\n"
        "- Titre, unite, periode, legende et source courte pour chaque visuel.\n"
        "Visuel utile : planche de graphiques coherente avec la charte.\n"
        "\n"
        "Chaque graphique est genere en HTML inline (sans <html>/<body>) a "
        "l'aide de tableaux HTML avec barres CSS. Voici le pattern a suivre "
        "(adapte les donnees reelles du projet) :\n"
        "<h3 style=\"font-size:14pt;margin:4mm 0 2mm\">Graphique 1 — Titre du graphique</h3>\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:3mm 0;font-size:9.5pt\">\n"
        "<tr><td style=\"padding:1.5mm 3mm;border-bottom:0.5pt solid #EFEAD8;width:35%\">Label A</td>"  # noqa: E501
        "<td style=\"padding:1.5mm 2mm;width:55%\">"
        "<div style=\"background:#C9A227;height:5mm;width:75%;display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold;color:#1A1A1A;width:10%\">75 %</td></tr>\n"
        "</table>\n"
        "Pour chaque graphique : titre H3, tableau barres avec valeurs reelles, "
        "legende courte sous le tableau en italique. Produis 3 a 5 graphiques "
        "(manuel §6, p. 15 : 3-5 visuels maximum) selectionnes selon le projet, "
        "en priorite parmi : (1) evolution du marche 2021-2026, (2) repartition "
        "CA cible par segment, (3) croissance projetee 2026-2030, (4) repartition "
        "clientele cible, (5) comparaison positionnement prix concurrents si disponible. "
        "Utilise les donnees chiffrees reelles etablies dans les chapitres precedents. "
        "Couleur principale des barres : #C9A227 (or EVKHA). Barres secondaires : #1A1A1A.\n"
        "\n"
        "CONTRAINTE ABSOLUE — coherence chiffres-fondations pour ce chapitre :\n"
        "Toutes les valeurs de taille de marche et de TCAC dans les graphiques "
        "DOIVENT correspondre exactement aux valeurs du bloc CHIFFRES_FONDATIONS. "
        "Distinction obligatoire : `taille_marche_mondial` (marche total mondial) "
        "et `taille_marche_continental` (part continentale) sont deux chiffres "
        "DIFFERENTS — ne les confonds pas dans les titres ou legendes des graphiques."
    ),
    "em.16.offre_demande": (
        "CHAPITRE 16 — Analyse de l'offre et de la demande (manuel §6, p. 15).\n"
        "Objectif : mesurer les tensions, manques et attentes mal couvertes sans "
        "basculer dans l'etude detaillee de la concurrence.\n"
        "Contenu obligatoire :\n"
        "- Volume ou intensite de la demande, saisonnalite, frequence et "
        "evolution.\n"
        "- Densite et typologie de l'offre existante.\n"
        "- Attentes satisfaites, insuffisamment satisfaites et non couvertes.\n"
        "- Tension par segment ou zone.\n"
        "Visuel utile : matrice besoins/couverture ou equilibre offre-demande.\n"
        "Rappel : ce chapitre reste une etude de marche, pas une etude detaillee "
        "de la concurrence."
    ),
    "em.17.geographique_avancee": (
        "CHAPITRE 17 — Analyse geographique avancee (manuel §6, p. 15).\n"
        "Objectif : prioriser les zones de lancement ou d'expansion a partir de "
        "criteres objectifs.\n"
        "Contenu obligatoire :\n"
        "- Criteres ponderes : demande, solvabilite, densite, accessibilite, "
        "concurrence, couts et reglementation.\n"
        "- Zones prioritaires, secondaires et a eviter.\n"
        "- Donnees et score justifiant chaque recommandation.\n"
        "- Coherence avec la zone demandee par le client.\n"
        "Visuel utile : carte si donnees geographiques fiables ; sinon tableau "
        "de scoring."
    ),
    "em.18.swot": (
        "CHAPITRE 18 — SWOT de synthese (manuel §6, p. 16).\n"
        "Objectif : resumer les enseignements etablis, sans inventer de nouveaux "
        "elements.\n"
        "Contenu obligatoire :\n"
        "- 3 a 5 forces, faiblesses, opportunites et menaces.\n"
        "- Origine tracable de chaque point dans un chapitre precedent.\n"
        "- Distinction interne/externe respectee.\n"
        "- Lecture croisee : forces pour saisir les opportunites, faiblesses "
        "face aux menaces.\n"
        "Visuel utile : matrice SWOT 2 x 2 lisible.\n"
        "\n"
        "Commence par 1 paragraphe d'introduction. Puis genere le tableau SWOT "
        "visuel 4 cases en HTML inline (sans <html>/<body>). Dans chaque cellule "
        "<td>, remplace les exemples par les vrais elements du projet. Chaque "
        "<li> = 1 a 2 phrases concretes et chiffrees.\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:4mm 0;font-size:9.5pt\">\n"
        "<tr>"
        "<th style=\"background:#2E7D4F;color:#fff;padding:3mm;text-align:center;width:50%"
        ";border:0.5pt solid #EFEAD8\">Forces</th>"
        "<th style=\"background:#B73E3E;color:#fff;padding:3mm;text-align:center;width:50%"
        ";border:0.5pt solid #EFEAD8\">Faiblesses</th>"
        "</tr>\n"
        "<tr>"
        "<td style=\"vertical-align:top;padding:3mm;border:0.5pt solid #EFEAD8\">"
        "<ul><li>Force 1 du projet : argument chiffre.</li>"
        "<li>Force 2 : avantage concret.</li>"
        "<li>Force 3 : atout specifique.</li></ul></td>"
        "<td style=\"vertical-align:top;padding:3mm;border:0.5pt solid #EFEAD8\">"
        "<ul><li>Faiblesse 1 : limite reelle a assumer.</li>"
        "<li>Faiblesse 2 : contrainte interne.</li>"
        "<li>Faiblesse 3 : risque structurel.</li></ul></td>"
        "</tr>\n"
        "<tr>"
        "<th style=\"background:#1565C0;color:#fff;padding:3mm;text-align:center"
        ";border:0.5pt solid #EFEAD8\">Opportunites</th>"
        "<th style=\"background:#E65100;color:#fff;padding:3mm;text-align:center"
        ";border:0.5pt solid #EFEAD8\">Menaces</th>"
        "</tr>\n"
        "<tr>"
        "<td style=\"vertical-align:top;padding:3mm;border:0.5pt solid #EFEAD8\">"
        "<ul><li>Opportunite 1 : tendance favorable chiffree.</li>"
        "<li>Opportunite 2 : marche non sature.</li>"
        "<li>Opportunite 3 : levier externe exploitable.</li></ul></td>"
        "<td style=\"vertical-align:top;padding:3mm;border:0.5pt solid #EFEAD8\">"
        "<ul><li>Menace 1 : risque sectoriel concret.</li>"
        "<li>Menace 2 : pression concurrentielle.</li>"
        "<li>Menace 3 : evolution reglementaire.</li></ul></td>"
        "</tr>\n"
        "</table>\n"
        "Remplis chaque cellule avec 3 a 5 points reels (manuel §6, p. 16 : "
        "3-5 forces, faiblesses, opportunites et menaces), specifiques au "
        "projet, pas generiques. Chaque point indique sa source dans l'etude. "
        "Apres le tableau, ajoute un paragraphe de lecture croisee : comment "
        "les forces compensent les faiblesses, comment les opportunites "
        "repondent aux menaces.\n"
        "\n"
        "CONTRAINTE — chiffres de marche dans ce chapitre :\n"
        "Quand tu mentionnes une taille de marche dans les opportunites ou menaces, "
        "utilise EXACTEMENT les valeurs du bloc CHIFFRES_FONDATIONS. "
        "Distinction critique : `taille_marche_mondial` (marche total mondial) "
        "et `taille_marche_continental` (part continentale, ex. Europe IA strict) "
        "sont deux chiffres differents. Labellise chacun avec son perimetre exact "
        "(ex. 'marche europeen IA 407 MEUR', jamais 'marche mondial 407 MEUR' "
        "si 407 MEUR est la valeur continentale)."
    ),
    "em.19.recommandations": (
        "CHAPITRE 19 — Analyse strategique et recommandations (manuel §6, p. 16).\n"
        "Objectif : transformer l'etude en decisions hierarchisees, realistes "
        "et immediatement actionnables.\n"
        "Contenu obligatoire :\n"
        "- Position du projet face au marche et niveau de differenciation.\n"
        "- Strategie de lancement ou developpement recommandee.\n"
        "- Risques critiques a traiter.\n"
        "- 5 a 7 recommandations avec priorite, horizon et justification.\n"
        "Visuel utile : feuille de route 90 jours / 12 mois / 24 mois."
    ),
    "em.20.conclusion": (
        "CHAPITRE 20 — Conclusion analytique (manuel §6, p. 16).\n"
        "Objectif : donner une lecture globale et nuancee du potentiel du "
        "marche et des conditions de reussite.\n"
        "Contenu obligatoire :\n"
        "- Situation du marche, opportunites, risques et pertinence du projet.\n"
        "- Reponse synthetique aux principales demandes du client.\n"
        "- Conditions necessaires a la reussite et elements a securiser.\n"
        "- Avis strategique clair et argumente.\n"
        "Visuel utile : encadre final « Potentiel / Conditions / Vigilances ».\n"
        "Rappel : la conclusion ne doit ajouter aucun chiffre, risque ou conseil "
        "qui n'apparait pas deja dans un chapitre precedent.\n"
        "\n"
        "CONTRAINTE — chiffres de marche dans ce chapitre :\n"
        "Toutes les tailles de marche citees DOIVENT etre les valeurs exactes du "
        "bloc CHIFFRES_FONDATIONS. Distinction critique : `taille_marche_mondial` "
        "(marche total mondial) et `taille_marche_continental` (part continentale) "
        "sont deux chiffres differents avec deux perimetres differents. "
        "Labellise chacun explicitement (ex. 'marche europeen IA X MEUR', "
        "'marche mondial Y Md EUR'). Ne substitue jamais l'un a l'autre."
    ),
    # em.21.annexe_brief : SUPPRIMEE le 24/07/2026 avec l'adoption du manuel
    # Evangeline. Les reponses aux demandes du client sont desormais integrees
    # dans les chapitres analytiques (verifiees par les CHECK 2/6/9) — cf.
    # blueprint MARKET_STUDY_CHAPTERS.
    # em.22.sources : renommee en em.21.sources_methodologie (fusion sources
    # + methodologie, chapitre 21 du manuel §6, p. 17).
    "em.21.sources_methodologie": (
        "CHAPITRE 21 — Sources et methodologie (manuel §6, p. 17).\n"
        "Objectif : rendre la recherche verifiable et expliquer sobrement les "
        "methodes d'estimation.\n"
        "Contenu obligatoire :\n"
        "- Liste dedupliquee des sources par famille (Marche, Demographie, "
        "Reglementation, Concurrence, Documents client). Pour chaque source : "
        "titre, organisme, annee et URL verifiee. Reprends en PRIORITE les URLs "
        "reelles du bloc SOURCES_WEB du contexte.\n"
        "- Courte methodologie : demarche de recherche, croisement de sources, "
        "periode des donnees, estimations construites (secteur adjacent, zone "
        "geographique proche, indicateur equivalent) et limites de l'etude.\n"
        "- Mention sobre des calculs EVKHA (TAM/SAM/SOM, scenarios) sans "
        "detailler la pipeline technique.\n"
        "Format :\n"
        "## Marche\n- Nom de la source, organisme, annee - https://...\n"
        "## Demographie\n- ...\n"
        "## Methodologie\nUn a deux paragraphes decrivant la demarche, les "
        "croisements et les limites. Pour chaque hypothese chiffree construite "
        "faute de source directe, indiquer la methode d'estimation.\n"
        "Aucun visuel obligatoire. Mise en page bibliographique claire. "
        "N'utilise JAMAIS les formules « URL a confirmer », « lien "
        "indisponible », « donnees non disponibles » : sans source, ne cite "
        "pas la donnee dans le corps du document.\n"
        "Si le bloc SOURCES_WEB du contexte est vide ou incomplet, utilise les "
        "patterns d'URL institutionnelles suivants (qui existent et sont stables) :\n"
        "- Reglementation UE : https://eur-lex.europa.eu/\n"
        "- Statistiques europeennes : https://ec.europa.eu/eurostat/\n"
        "- OCDE donnees : https://data.oecd.org/\n"
        "- INSEE France : https://www.insee.fr/\n"
        "- Xerfi etudes sectorielles : https://www.xerfi.com/ (avec titre exact de "
        "l'etude si connue, sinon ne pas citer Xerfi)\n"
        "- Statista : https://www.statista.com/ (avec titre exact de la fiche)\n"
        "- McKinsey Global Institute : https://www.mckinsey.com/mgi/\n"
        "Pour les sources sectorielles dont tu ne connais pas l'URL precise, "
        "cite uniquement le nom de l'organisme et l'annee sans URL. Ne pas "
        "inventer d'URL."
    ),
    # --- Sections de generation par chunks (chapitres denses) ---------------
    # Chaque section est generee separement puis fusionnee en un seul chapitre.
    # Les prompts sont volontairement cibles sur un sous-perimetre pour eviter
    # la troncature et maximiser la densite informationnelle par appel.
    "em.01.a.mondial": (
        "SECTION 1.a — Dimension MONDIALE du marche (manuel §6 ch. 1, p. 8).\n"
        "Objectif : etablir la taille, la croissance et les dynamiques du "
        "marche a l'echelle mondiale, sans traiter le continent pertinent "
        "(qui fera l'objet de la section 1.b).\n"
        "Contenu obligatoire :\n"
        "- Definition exacte du marche et de son perimetre.\n"
        "- Taille actuelle en valeur (Mds € ou $), historique utile.\n"
        "- TCAC mondial calcule ou verifie sur les 3 a 5 dernieres annees.\n"
        "- Repartition geographique globale (zones dominantes) et moteurs de "
        "croissance.\n"
        "Toutes les donnees chiffrees et sourcees. Distingue faits observes, "
        "estimations et projections.\n"
        "\n"
        "CONTRAINTE DE LABELLISATION — critique pour la coherence de toute l'etude :\n"
        "La valeur que tu annonces comme taille du marche mondial dans cette section "
        "sera verrouilee automatiquement comme `taille_marche_mondial` et reutilisee "
        "dans les 20 chapitres suivants. Il est donc interdit de :\n"
        "- Mentionner dans la meme phrase la taille mondiale ET un sous-perimetre "
        "geographique (continental, regional) avec une valeur differente, car "
        "l'extracteur peut confondre les deux niveaux.\n"
        "- Decrire une valeur continentale ou regionale en utilisant le mot 'mondial'.\n"
        "Regle : une phrase = un perimetre geographique = une valeur. "
        "Le marche mondial doit apparaitre dans une phrase ou 'mondial' (ou son "
        "equivalent : global, international) est le seul qualificatif geographique."
    ),
    "em.01.b.europeen": (
        "SECTION 1.b — Continent pertinent pour le projet (manuel §6 ch. 1, p. 8).\n"
        "Objectif : analyser la dimension CONTINENTALE reellement pertinente "
        "pour le projet — souvent l'Europe pour un projet francais, mais peut "
        "etre l'Afrique de l'Ouest, l'Amerique du Nord, etc. selon PAYS. Ne "
        "choisis pas l'Europe par defaut. Prolonge la section 1.a sans "
        "repeter les chiffres mondiaux.\n"
        "Contenu obligatoire :\n"
        "- Taille du marche sur le continent pertinent, TCAC continental.\n"
        "- Top pays du continent par volume ou valeur.\n"
        "- Specificites reglementaires ou culturelles utiles au projet.\n"
        "- Acteurs continentaux dominants et parts de marche estimees.\n"
        "- Projection prudente a 2030 avec hypotheses.\n"
        "Visuel utile (manuel) : courbe historique et projection, monde "
        "versus continent pertinent. Genere UN graphique HTML en barres "
        "montrant l'evolution 2021-2026 sur le continent pertinent, en "
        "utilisant ce pattern exact (adapte valeurs et etiquettes reelles) :\n"
        "<h3 style=\"font-size:13pt;margin:4mm 0 2mm\">Evolution du marche — 2021 a 2026</h3>\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:3mm 0;font-size:9pt\">\n"
        "<tr><td style=\"padding:1.5mm 3mm;border-bottom:0.5pt solid #EFEAD8;width:12%\">2021</td>"
        "<td style=\"padding:1.5mm 2mm;width:78%\">"
        "<div style=\"background:#C9A227;height:5mm;width:60%;display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold;width:10%\">XX Md€</td></tr>\n"
        "<tr><td style=\"padding:1.5mm 3mm;border-bottom:0.5pt solid #EFEAD8\">2022</td>"
        "<td style=\"padding:1.5mm 2mm\">"
        "<div style=\"background:#C9A227;height:5mm;width:65%;display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold\">XX Md€</td></tr>\n"
        "<tr><td style=\"padding:1.5mm 3mm;border-bottom:0.5pt solid #EFEAD8\">2023</td>"
        "<td style=\"padding:1.5mm 2mm\">"
        "<div style=\"background:#C9A227;height:5mm;width:70%;display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold\">XX Md€</td></tr>\n"
        "<tr><td style=\"padding:1.5mm 3mm;border-bottom:0.5pt solid #EFEAD8\">2024</td>"
        "<td style=\"padding:1.5mm 2mm\">"
        "<div style=\"background:#C9A227;height:5mm;width:78%;display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold\">XX Md€</td></tr>\n"
        "<tr><td style=\"padding:1.5mm 3mm;border-bottom:0.5pt solid #EFEAD8\">2025</td>"
        "<td style=\"padding:1.5mm 2mm\">"
        "<div style=\"background:#1A1A1A;height:5mm;width:86%;display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold\">XX Md€ est.</td></tr>\n"
        "<tr><td style=\"padding:1.5mm 3mm\">2026</td>"
        "<td style=\"padding:1.5mm 2mm\">"
        "<div style=\"background:#1A1A1A;height:5mm;width:93%;display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold\">XX Md€ proj.</td></tr>\n"
        "</table>\n"
        "<p style=\"font-style:italic;font-size:8.5pt;color:#5A5A5A\">Sources : [cite tes sources]. "  # noqa: E501
        "Est. = estimation. Proj. = projection argumentee.</p>\n"
        "Remplace chaque XX par les vraies valeurs etablies dans l'analyse.\n"
        "\n"
        "CONTRAINTE DE LABELLISATION — critique pour la coherence de toute l'etude :\n"
        "La valeur que tu annonces comme taille du marche continental dans cette "
        "section sera verrouilee automatiquement comme `taille_marche_continental` "
        "et reutilisee dans les chapitres 2, 8, 9, 15, 18 et 20. Il est donc "
        "interdit de :\n"
        "- Decrire la valeur continentale avec le mot 'mondial' dans la meme phrase "
        "(ex. interdit : 'le marche mondial europeen represente X MEUR' — correct : "
        "'le marche europeen represente X MEUR, soit Y % du marche mondial').\n"
        "- Presenter la valeur continentale comme etant la taille totale du marche.\n"
        "Regle : nomme explicitement le continent dans la phrase qui annonce la valeur "
        "continentale (ex. 'Europe', 'Afrique subsaharienne', 'Amerique du Nord'). "
        "Les chapitres suivants prendront ce chiffre comme reference continentale — "
        "s'il est mislabellise comme 'mondial', tous les chapitres posterieurs "
        "repeteront cette erreur."
    ),
    "em.10.a.profil_besoins": (
        "SECTION 10.a — Produits ou prestations les plus recherches par la "
        "cible (manuel §6 ch. 10, p. 13).\n"
        "Objectif : identifier ce que les clients recherchent reellement, "
        "avant d'analyser leurs comportements d'achat.\n"
        "Contenu obligatoire :\n"
        "- Profil demographique et socio-economique de la clientele cible : "
        "tranche d'age dominante, genre, CSP, niveau de revenu, zone.\n"
        "- Produits ou prestations les plus recherches, hierarchises.\n"
        "- Besoins primaires (mal couverts) et secondaires que le projet "
        "peut resoudre.\n"
        "- Taille estimee du segment cible en nombre ou en valeur.\n"
        "Ne traite pas les comportements d'achat ni les criteres de decision "
        "(sections 10.b et 10.c)."
    ),
    "em.10.b.comportements": (
        "SECTION 10.b — Frequence, cycle et saisonnalite d'achat "
        "(manuel §6 ch. 10, p. 13).\n"
        "Objectif : decrire concretement comment la cible achete ou utilise "
        "les produits/services.\n"
        "Contenu obligatoire :\n"
        "- Frequence d'achat ou d'usage (recurrent, occasionnel, ponctuel).\n"
        "- Cycle de decision (rapide, reflechi, long).\n"
        "- Saisonnalite et evenements declencheurs.\n"
        "- Canaux d'achat preferes (physique, digital, mixte) et parcours "
        "client type du besoin a l'acte d'achat.\n"
        "- Panier moyen ou prix moyen paye actuellement, lorsque documente.\n"
        "Ne repete pas le profil ni les criteres de decision."
    ),
    "em.10.c.criteres_decision": (
        "SECTION 10.c — Motivations, freins, criteres de confiance et role "
        "des avis (manuel §6 ch. 10, p. 13).\n"
        "Objectif : comprendre les leviers et obstacles a la conversion.\n"
        "Contenu obligatoire :\n"
        "- Motivations d'achat (rationnelles, emotionnelles, sociales).\n"
        "- Freins et objections (prix, confiance, changement d'habitude).\n"
        "- Criteres de confiance : marque, certifications, garanties, "
        "recommandations.\n"
        "- Role des avis clients et bouche-a-oreille dans la decision.\n"
        "- Sensibilite au prix (elasticite) et fourchettes acceptables "
        "lorsque pertinent, sans jamais inventer un chiffre.\n"
        "Visuel utile (manuel) : parcours de decision ou matrice "
        "attentes/freins/leviers."
    ),
    "em.14.a.hypotheses": (
        "SECTION 14.a — Adequation besoin/offre, cible et differenciation "
        "(manuel §6 ch. 14, p. 14).\n"
        "Objectif : evaluer si le projet repond a un besoin reel et "
        "accessible, SANS remplacer le previsionnel financier.\n"
        "Contenu obligatoire :\n"
        "- Adequation entre le besoin identifie (ch. 10) et l'offre du "
        "projet : le projet resout-il un vrai probleme de la cible ?\n"
        "- Accessibilite de la cible : canaux, cout d'acquisition estime, "
        "acceptation prevue.\n"
        "- Capacite de differenciation vis-a-vis de l'offre existante "
        "(ch. 16), sans basculer en etude concurrentielle detaillee.\n"
        "Aucune hypothese chiffree de type CA/EBE/resultat net : ce chapitre "
        "n'est PAS un mini-business plan. Utilise le SOM du ch. 2 et les "
        "reperes de comportement du ch. 10."
    ),
    "em.14.b.projections": (
        "SECTION 14.b — Compatibilite entre SOM, ressources, cycle de vente "
        "et modele economique (manuel §6 ch. 14, p. 14).\n"
        "Objectif : verifier que le potentiel accessible est reellement "
        "atteignable compte tenu des ressources et du modele du porteur.\n"
        "Contenu obligatoire :\n"
        "- Rappel du SOM annee 1 et annee 3 verrouilles au ch. 2 (aucune "
        "nouvelle valeur).\n"
        "- Compatibilite avec les ressources connues du porteur (capacite "
        "de production, effectif, budget marketing).\n"
        "- Cohérence avec le cycle de vente identifie au ch. 10 (rapide vs "
        "long, saisonnalite).\n"
        "- Alignement avec le modele economique declare (vente directe, "
        "abonnement, marketplace, mixte).\n"
        "Aucune projection financiere chiffree : le previsionnel appartient "
        "au business plan, pas a l'etude de marche."
    ),
    "em.14.c.viabilite": (
        "SECTION 14.c — Facteurs de resilience, dependances critiques et "
        "seuils de vigilance (manuel §6 ch. 14, p. 14).\n"
        "Objectif : identifier ce qui rend le projet durable ou fragile face "
        "au marche, sans inventer de prevision chiffree.\n"
        "Contenu obligatoire :\n"
        "- Facteurs de resilience : elements qui rendent le projet robuste "
        "aux chocs (diversite clientele, pouvoir de pricing, position sur "
        "un besoin structurel).\n"
        "- Dependances critiques : fournisseurs uniques, plateformes tierces, "
        "reglementations, cible etroite.\n"
        "- Seuils ou conditions de vigilance lorsque defendables (par "
        "exemple : « au-dela d'une baisse de 20 % de la demande locale, "
        "le SOM annee 1 devient insoutenable »).\n"
        "Visuel utile (manuel) : scorecard de viabilite avec justification, "
        "jamais un score decoratif. Rappel : aucun previsionnel financier."
    ),
    "em.19.a.diagnostic": (
        "SECTION 19.a — Position du projet face au marche, strategie de "
        "lancement et risques critiques (manuel §6 ch. 19, p. 16).\n"
        "Objectif : etablir un diagnostic strategique synthetique base sur "
        "les enseignements des chapitres precedents. AUCUN nouveau chiffre.\n"
        "Contenu obligatoire (les trois points du manuel) :\n"
        "- Position du projet face au marche et niveau de differenciation : "
        "force relative, avantage differenciant, gaps a combler (cites "
        "depuis les chapitres precedents).\n"
        "- Strategie de lancement ou developpement recommandee : quelle "
        "approche privilegier pour entrer sur le marche ou developper "
        "l'activite, en coherence avec le SOM, la cible et les ressources.\n"
        "- Risques critiques a traiter avant le lancement (extraits du "
        "ch. 12 et de la cartographie ch. 13).\n"
        "Sois direct, sans complaisance. Reste redige, pas une liste de puces."
    ),
    "em.19.b.plan_action": (
        "SECTION 19.b — 5 a 7 recommandations avec priorite, horizon et "
        "justification (manuel §6 ch. 19, p. 16).\n"
        "Objectif : transformer le diagnostic en decisions concretes et "
        "immediatement actionnables.\n"
        "Contenu obligatoire :\n"
        "- 5 a 7 recommandations hierarchisees. Pour chacune : quoi faire, "
        "priorite, horizon et justification issue de l'etude.\n"
        "Visuel utile (manuel) : feuille de route 90 jours / 12 mois / "
        "24 mois. Reste realiste : chaque recommandation doit etre "
        "executable avec les ressources connues du porteur."
    ),
}

# --- Etude de la concurrence (EC) ----------------------------------------

COMPETITOR_STUDY_PROMPTS: dict[str, str] = {
    "ec.00.fiche_projet": (
        "FORMAT STRICT (Bloc 5 Consignes EVKHA) : produis EXACTEMENT un tableau "
        "Markdown a 2 colonnes (Label | Valeur), AUCUN texte autour, AUCUNE "
        "introduction, AUCUN commentaire. Les 8 lignes obligatoires dans cet "
        "ordre exact :\n"
        "| Élément | Détail |\n"
        "|---|---|\n"
        "| Secteur | [valeur] |\n"
        "| Pays | [valeur] |\n"
        "| Projet | [description en 1-2 phrases] |\n"
        "| Zone | [valeur] |\n"
        "| Positionnement | [synthese 1 phrase] |\n"
        "| Clientèle cible | [synthese 1 phrase] |\n"
        "| Modèle économique | [synthese 1 phrase] |\n"
        "| Éléments à retenir | [3 a 5 points cles separes par ' / '] |\n"
        "Apres le tableau, saute une ligne et ajoute UNE SEULE section "
        "intitulee '## Questions auxquelles cette etude repond' avec une liste "
        "a puces de 4 a 5 questions implicites du porteur orientees benchmark "
        "concurrentiel (type 'Qui sont les concurrents directs les plus serieux ?'). "
        "Rien d'autre."
    ),
    "ec.01.identification": (
        "Identification rigoureuse des concurrents directs (meme offre, meme "
        "cible) et indirects (substituts). Le nombre final DOIT toujours etre "
        "EXACTEMENT 8 concurrents directs et 3 indirects, ni plus, ni moins. "
        "REGLE D'EXCLUSIVITE ABSOLUE : un meme acteur NE PEUT PAS figurer a la "
        "fois dans les directs ET les indirects. Si un acteur semble appartenir "
        "aux deux categories, classe-le dans celle qui reflete sa principale "
        "modalite de concurrence (direct = meme offre ET meme cible ; indirect "
        "= substitut ou cible adjacente). Verifie avant de finaliser qu'aucun "
        "nom n'apparait dans les deux listes. "
        "Si VARIABLES_PROJET.CONCURRENTS propose des noms, ne les traite jamais "
        "tous integralement : selectionne parmi eux les 8 directs et les 3 "
        "indirects les plus pertinents pour ce projet (proximite d'offre, de "
        "cible, d'implantation), meme si la liste en propose davantage (10, 15, "
        "20...). Si cette liste est vide, trop vague ou insuffisante pour "
        "atteindre 8 directs + 3 indirects, complete-la toi-meme avec des "
        "acteurs reels et plausibles du secteur et de la zone du projet pour "
        "atteindre exactement ce nombre, et poursuis l'etude normalement : ne "
        "t'arrete jamais et ne reduis jamais le nombre de concurrents traites "
        "faute d'indication du client. Pour chacun : nom, emplacement precis, "
        "site web. Termine par une base consolidee (type, structure, "
        "positionnement, CA connu ou estime + fiabilite)."
    ),
    # ec.02 decoupe en 2 sections : 8 directs d'abord, puis 3 indirects.
    # Evite la troncature (11 concurrents x (3F + 3F + VA) depasse 3500 tokens).
    "ec.02.classement_qualitatif": (
        "Ce chapitre est genere en deux sections distinctes. "
        "Ne pas utiliser ce prompt directement."
    ),
    "ec.02.a.directs": (
        "Classement et analyse qualitative des 8 CONCURRENTS DIRECTS "
        "identifies au chapitre 1. "
        "REGLE DE COHERENCE ABSOLUE : reprends EXACTEMENT les 8 memes noms "
        "de concurrents que ceux listes au chapitre 1 (RESUME_OPERATIONNEL_"
        "PRECEDENT), dans le meme ordre, avec la meme orthographe. Aucun "
        "ajout, aucun retrait, aucune substitution. Si tu doutes du nom "
        "exact, va le relire dans le resume operationnel avant de rediger. "
        "Traite IMPERATIVEMENT chacun des 8, dans l'ordre du chapitre 1. "
        "Pour chaque direct (sous-titre ### 2.1 a ### 2.8) : "
        "— Presence geographique et structure d'implantation "
        "— Positionnement tarifaire et segment cible "
        "— 3 FORCES principales (concretes, documentees) "
        "— 3 FAIBLESSES principales (concretes, actionnables) "
        "— 1 Valeur ajoutee differenciante exploitable pour le projet. "
        "Ne t'arrete pas avant d'avoir couvert le concurrent 8."
    ),
    "ec.02.b.indirects": (
        "Classement et analyse qualitative des 3 CONCURRENTS INDIRECTS "
        "identifies au chapitre 1. "
        "REGLE DE COHERENCE ABSOLUE : reprends EXACTEMENT les 3 memes noms "
        "que ceux listes au chapitre 1 (RESUME_OPERATIONNEL_PRECEDENT), "
        "dans le meme ordre, meme orthographe. Aucun ajout ni retrait. "
        "Traite IMPERATIVEMENT les 3, dans l'ordre du chapitre 1. "
        "Pour chaque indirect (sous-titre ### 2.9, ### 2.10, ### 2.11) : "
        "— Nature de la concurrence indirecte "
        "— Presence geographique et positionnement "
        "— 3 FORCES, 3 FAIBLESSES "
        "— 1 Valeur ajoutee differenciante pour le projet."
    ),
    # ec.03 est decoupe en 2 sections pour garantir la couverture complete
    # des 8 directs + 3 indirects sans troncature.
    "ec.03.approfondissement": (
        "Ce chapitre est genere en deux sections distinctes. "
        "Ne pas utiliser ce prompt directement."
    ),
    "ec.03.a.directs": (
        "Approfondissement strategique des 8 CONCURRENTS DIRECTS identifies au chapitre 1. "
        "REGLE DE COHERENCE ABSOLUE : les 8 noms doivent etre les MEMES qu'au "
        "chapitre 1 et au chapitre 2, meme orthographe, meme ordre. Verifie "
        "dans RESUME_OPERATIONNEL_PRECEDENT avant de rediger — toute variation "
        "de nom ou d'ordre cree une incoherence editoriale majeure. "
        "Traite IMPERATIVEMENT chacun des 8, dans leur ordre d'apparition au chapitre 1, "
        "sans en sauter ni en fusionner. "
        "Pour chaque concurrent direct (numeroter les sous-titres : ### 3.1, ### 3.2... ### 3.8) : "
        "— Positionnement global (proposition de valeur, cible, prix, geographie) "
        "— Synthese des avis clients reels : points forts recurrents, points negatifs recurrents, "
        "   enseignements actionnables pour le projet "
        "— Innovations et technologies deployees (e-commerce, CRM, IA, outils digitaux) "
        "— Tendances et orientations strategiques recentes "
        "— Initiatives RSE et engagement societaux "
        "Si tu n'as pas encore traite le concurrent 8, continue — ne t'arrete pas avant. "
        "GRAPHIQUE OBLIGATOIRE : apres avoir traite les 8 concurrents directs, "
        "insere un bloc ```chart de type 'radar' comparant les 3 concurrents "
        "les plus significatifs (ceux avec le plus fort impact sur le projet) "
        "sur 5 criteres : Notoriete, Positionnement prix, Digital, Innovation, "
        "Engagement RSE. Valeurs de 0 a 5 (echelle qualitative). labels sont "
        "les 5 criteres, series contient une entree par concurrent avec ses "
        "5 values. Ce radar sert de synthese visuelle avant le chapitre "
        "suivant."
    ),
    "ec.03.b.indirects": (
        "Approfondissement strategique des 3 CONCURRENTS INDIRECTS identifies au chapitre 1. "
        "Traite IMPERATIVEMENT les 3, dans leur ordre d'apparition au chapitre 1. "
        "Pour chaque concurrent indirect (sous-titres : ### 3.9, ### 3.10, ### 3.11) : "
        "— Nature de la concurrence indirecte "
        "(en quoi ils captent une partie de la clientele cible) "
        "— Positionnement global et proposition de valeur "
        "— Synthese des avis clients et enseignements pour le projet "
        "— Innovations ou avantages comparatifs notables "
        "— Ce que leur modele implique strategiquement pour le projet "
        "Termine la section par un paragraphe de synthese comparant concurrents directs "
        "et indirects : zones de friction, d'opportunite et lecons strategiques globales."
    ),
    "ec.04.positionnement_annexes": (
        "Positionnement differenciant recommande pour le projet face aux "
        "concurrents, puis 3 a 4 annexes strategiques pretes a inserer (canaux "
        "de communication, comparatif avis clients, analyse juridique, benchmark "
        "digital...)."
    ),
    "ec.05.matrice_positionnement": (
        "Matrice de positionnement concurrentiel : choisis 2 axes strategiques "
        "pertinents (ex. prix / qualite percue, ou positionnement premium / "
        "accessible). "
        "ETAPE OBLIGATOIRE : le tableau HTML ci-dessous DOIT apparaitre dans ta "
        "reponse, rempli avec les donnees reelles. Ce n'est pas une option ni un "
        "exemple a paraphraser : une reponse qui decrit la matrice uniquement en "
        "texte, sans le tableau HTML, est un echec. Le contenu de chaque cellule "
        "reste court (une ligne, style fiche : nom de l'acteur + 3-6 mots de "
        "qualification), jamais un paragraphe complet — les paragraphes "
        "d'interpretation viennent APRES le tableau, pas dedans. "
        "Genere d'abord la matrice en HTML inline (sans <html>/<body>) sous forme "
        "de grille 3x3 representant les 4 quadrants autour d'un centre, chaque "
        "concurrent et le projet places dans la cellule correspondant a sa "
        "position reelle. Voici le pattern a suivre (adapte les libelles d'axes "
        "et le contenu des cellules aux donnees reelles) :\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:4mm 0;"
        "font-size:9pt;table-layout:fixed\">\n"
        "<tr><td colspan=\"3\" style=\"text-align:center;padding:1mm;"
        "font-weight:bold;color:#1A1A1A\">Axe vertical (ex. Qualite percue +)</td>"
        "</tr>\n"
        "<tr>"
        "<td style=\"height:28mm;vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#FBF8EF\">Acteur A</td>"
        "<td style=\"height:28mm;vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#FBF8EF\">Acteur B</td>"
        "<td style=\"height:28mm;vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#FBF8EF\">Acteur C</td>"
        "</tr>\n"
        "<tr>"
        "<td style=\"height:28mm;vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8\">Acteur D</td>"
        "<td style=\"height:28mm;vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#C9A22733;font-weight:bold;"
        "color:#1A1A1A\">Projet (position visee)</td>"
        "<td style=\"height:28mm;vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8\">Acteur E</td>"
        "</tr>\n"
        "<tr>"
        "<td style=\"height:28mm;vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#FBF8EF\">Acteur F</td>"
        "<td style=\"height:28mm;vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#FBF8EF\">Acteur G</td>"
        "<td style=\"height:28mm;vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#FBF8EF\">Acteur H</td>"
        "</tr>\n"
        "<tr><td colspan=\"3\" style=\"text-align:center;padding:1mm;"
        "font-weight:bold;color:#1A1A1A\">Axe horizontal (ex. Prix bas -&gt; Prix eleve)</td>"
        "</tr>\n"
        "</table>\n"
        "Place chaque concurrent identifie dans les chapitres precedents dans la "
        "cellule qui correspond a sa position reelle sur les 2 axes (n'utilise pas "
        "obligatoirement les 9 cellules, ne remplis que celles pertinentes, "
        "laisse une cellule vide plutot que d'inventer un acteur). Mets le projet "
        "en surbrillance (couleur #C9A22733) dans la cellule visee. "
        "Apres la matrice, interprete en 2 a 3 paragraphes : zones saturees, "
        "espaces libres, risques de cannibalisation."
    ),
    "ec.06.parts_de_marche": (
        "Estimation des chiffres d'affaires et parts de marche : CA connus "
        "(annee + source + fiabilite), estimations argumentees pour les acteurs "
        "non references, projection des parts de marche locales et lecture "
        "(qui domine, qui emerge, qui recule)."
    ),
    "ec.07.conclusion_graphiques": (
        "Conclusion analytique : forces/faiblesses majeures du marche "
        "concurrentiel, axe strategique prioritaire pour le projet, leviers "
        "differenciants des le lancement. "
        "Avant la conclusion textuelle, genere 4 graphiques en HTML inline (sans "
        "<html>/<body>) a l'aide de tableaux HTML avec barres CSS, sur le meme "
        "modele que les graphiques du chapitre marche : titre H3, tableau barres "
        "avec valeurs reelles, legende courte en italique sous chaque tableau. "
        "Pattern a suivre pour chaque graphique en barres (adapte les donnees "
        "reelles) :\n"
        "<h3 style=\"font-size:14pt;margin:4mm 0 2mm\">Graphique 1 — Titre</h3>\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:3mm 0;"
        "font-size:9.5pt\">\n"
        "<tr><td style=\"padding:1.5mm 3mm;border-bottom:0.5pt solid #EFEAD8;"
        "width:35%\">Label A</td>"
        "<td style=\"padding:1.5mm 2mm;width:55%\">"
        "<div style=\"background:#C9A227;height:5mm;width:75%;"
        "display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold;color:#1A1A1A;width:10%\">"
        "75 %</td></tr>\n"
        "</table>\n"
        "Les 4 graphiques a produire : "
        "(1) parts de marche des principaux concurrents identifies (barres, %), "
        "(2) repartition des canaux de distribution/acquisition du marche "
        "(barres, %), "
        "(3) comparatif forces/faiblesses des 2-3 concurrents principaux face au "
        "projet : une ligne par critere (prix, qualite, notoriete, digital...), "
        "une barre par acteur avec sa couleur propre (#C9A227 pour le projet, "
        "#1A1A1A pour les concurrents), "
        "(4) carte synthetique des concurrents par categorie (directs, indirects, "
        "emergents) sous forme de tableau a 3 colonnes listant les acteurs de "
        "chaque categorie. "
        "Utilise les donnees chiffrees reelles etablies dans les chapitres "
        "precedents, jamais de valeurs inventees sans base. "
        "Termine par la conclusion analytique textuelle demandee ci-dessus."
    ),
    "ec.08.annexe_brief": (
        "Annexe finale : pour chaque demande specifique du client, indique si "
        "elle est traitee, partiellement traitee ou non traitee, avec une phrase "
        "explicative le cas echeant."
    ),
    "ec.09.sources": (
        "Liste les sources reellement utilisees pour cette etude concurrentielle, "
        "regroupees par thematique (Concurrents identifies, Donnees de marche, "
        "Avis clients, Publications sectorielles). Reprends en PRIORITE les URLs "
        "reelles du bloc SOURCES_WEB du contexte ; n'invente aucune URL absente "
        "de ce bloc. Format simple :\n"
        "## Concurrents identifies\n- Nom - URL si disponible\n"
        "## Donnees de marche\n- ...\n"
        "Pas plus de 4-6 sources par thematique. Ajoute un court paragraphe "
        "'## Methodologie' (3-4 lignes) expliquant la demarche de benchmark "
        "(perimetre, critere de selection des concurrents, periode des avis). "
        "Rester concis et structure."
    ),
}


# --- Business Plan (BP) --------------------------------------------------
# Prompts alignes avec la spec officielle EVKHA V1 (mai 2026).
# Chapitres 2-11 bases sur les objectifs de la spec ; chapitres 12-19
# bases sur le squelette FIRE EVENT valide. Ton : narratif, ecrit comme
# si le porteur s'exprimait lui-meme, credible pour un banquier/investisseur.
# Ne jamais ecrire "Etape", "Validation", "Pipeline" ni tout marqueur interne.

BUSINESS_PLAN_PROMPTS: dict[str, str] = {
    "bp.00.fiche_projet": (
        "FORMAT STRICT (Bloc 5 Consignes EVKHA) : produis EXACTEMENT un tableau "
        "Markdown a 2 colonnes (Label | Valeur), AUCUN texte autour, AUCUNE "
        "introduction, AUCUN commentaire. Les 8 lignes obligatoires dans cet "
        "ordre exact :\n"
        "| Élément | Détail |\n"
        "|---|---|\n"
        "| Secteur | [valeur] |\n"
        "| Pays | [valeur] |\n"
        "| Projet | [description en 1-2 phrases] |\n"
        "| Zone | [valeur] |\n"
        "| Positionnement | [synthese 1 phrase] |\n"
        "| Clientèle cible | [synthese 1 phrase] |\n"
        "| Modèle économique | [synthese 1 phrase] |\n"
        "| Éléments à retenir | [3 a 5 points cles separes par ' / '] |\n"
        "Apres le tableau, saute une ligne et ajoute UNE SEULE section "
        "intitulee '## Questions auxquelles ce business plan repond' avec une "
        "liste a puces de 4 a 5 questions implicites du porteur orientees "
        "viabilite et financement (type 'Le projet est-il rentable des l'annee 1 ?'). "
        "Rien d'autre."
    ),
    "bp.01.resume_executif": (
        "Resume executif (1 page maximum) : presentation synthetique du "
        "projet et de son activite, historique et contexte du demarrage, "
        "objectifs de creation ou de structuration, chiffres cles "
        "previsionnels sur 3 ans, vision globale et message central. "
        "Percutant et clair, ecrit comme si le porteur s'exprimait."
    ),
    "bp.02.porteur_projet": (
        "Presente le porteur de projet de maniere a construire sa "
        "legitimite entrepreneuriale, professionnelle et humaine : parcours, "
        "experience metier dans le secteur, competences techniques et "
        "operationnelles, vision entrepreneuriale, implication personnelle. "
        "Redigez comme un dirigeant en construction, pas comme un CV."
    ),
    "bp.03.genese_projet": (
        "Raconte l'histoire du projet depuis son origine : pourquoi ce "
        "projet existe, comment il s'est construit dans le temps, quelles "
        "etapes ont valide la demarche, pourquoi ce moment est le bon pour "
        "franchir l'etape actuelle. Cree une trajectoire credible et assumee."
    ),
    "bp.04.activite": (
        "Presente l'activite de maniere claire et structuree : ce que vend "
        "reellement l'entreprise, comment fonctionne l'activite, a quels "
        "besoins elle repond, a qui elle s'adresse, comment elle genere ses "
        "revenus. Le lecteur doit comprendre sans connaissance prealable du secteur."
    ),
    "bp.05.positionnement_concept": (
        "Definit clairement le positionnement strategique : quelle place le "
        "projet occupe sur son marche, a quels besoins precis il repond, "
        "pourquoi des clients choisiraient cette offre plutot qu'une autre, "
        "comment le projet se distingue concretement de la concurrence."
    ),
    "bp.06.marche_synthese": (
        "Synthese strategique du marche cible : taille et dynamique, "
        "segments prioritaires, tendances favorables au projet, clientele "
        "cible et ses besoins. Produit une lecture business claire, pas une "
        "etude exhaustive. Relie systematiquement les donnees au projet concret."
    ),
    "bp.07.concurrentielle": (
        "Lecture strategique du paysage concurrentiel : acteurs directs et "
        "indirects identifies et analyses, positionnement du projet par "
        "rapport a la concurrence, espaces strategiques disponibles, "
        "avantage differenciant defendable du projet. Nombre limite de "
        "concurrents (8 directs + 3 indirects maximum), traites avec rigueur."
    ),
    "bp.08.offre_commerciale": (
        "Presente concretement l'offre : ce qui est vendu, comment l'offre "
        "est structuree (niveaux, gammes, options), politique tarifaire et "
        "logique de prix moyen, coherence entre l'offre et le positionnement. "
        "Demontre que l'offre a ete pensee et economiquement reflechie."
    ),
    "bp.09.modele_bmc": (
        "Presente la logique economique globale : comment l'entreprise cree "
        "de la valeur, comment elle genere du chiffre d'affaires, structure "
        "des couts principaux, marge brute estimee, point mort. "
        "Puis genere le Business Model Canvas en HTML inline (sans "
        "<html>/<body>) sous forme de grille visuelle a 9 blocs. IMPORTANT : "
        "remplace les exemples par le contenu reel du projet, 2 a 3 elements "
        "concrets par bloc.\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:4mm 0;"
        "font-size:8.5pt;table-layout:fixed\">\n"
        "<tr>"
        "<td rowspan=\"2\" style=\"vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#FBF8EF\">"
        "<strong style=\"color:#1A1A1A\">Partenaires cles</strong>"
        "<ul><li>Element 1</li><li>Element 2</li></ul></td>"
        "<td style=\"vertical-align:top;padding:2mm;border:0.5pt solid #EFEAD8;"
        "background:#FBF8EF\"><strong style=\"color:#1A1A1A\">Activites cles"
        "</strong><ul><li>Element 1</li><li>Element 2</li></ul></td>"
        "<td rowspan=\"2\" style=\"vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#C9A22733\">"
        "<strong style=\"color:#1A1A1A\">Proposition de valeur</strong>"
        "<ul><li>Element 1</li><li>Element 2</li></ul></td>"
        "<td style=\"vertical-align:top;padding:2mm;border:0.5pt solid #EFEAD8;"
        "background:#FBF8EF\"><strong style=\"color:#1A1A1A\">Relation client"
        "</strong><ul><li>Element 1</li></ul></td>"
        "<td rowspan=\"2\" style=\"vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#FBF8EF\">"
        "<strong style=\"color:#1A1A1A\">Segments clients</strong>"
        "<ul><li>Element 1</li><li>Element 2</li></ul></td>"
        "</tr>\n"
        "<tr>"
        "<td style=\"vertical-align:top;padding:2mm;border:0.5pt solid #EFEAD8;"
        "background:#FBF8EF\"><strong style=\"color:#1A1A1A\">Ressources cles"
        "</strong><ul><li>Element 1</li></ul></td>"
        "<td style=\"vertical-align:top;padding:2mm;border:0.5pt solid #EFEAD8;"
        "background:#FBF8EF\"><strong style=\"color:#1A1A1A\">Canaux</strong>"
        "<ul><li>Element 1</li></ul></td>"
        "</tr>\n"
        "<tr>"
        "<td colspan=\"2\" style=\"vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#1A1A1A;color:#fff\">"
        "<strong>Structure de couts</strong><ul><li>Element 1</li>"
        "<li>Element 2</li></ul></td>"
        "<td colspan=\"3\" style=\"vertical-align:top;padding:2mm;"
        "border:0.5pt solid #EFEAD8;background:#1A1A1A;color:#fff\">"
        "<strong>Sources de revenus</strong><ul><li>Element 1</li>"
        "<li>Element 2</li></ul></td>"
        "</tr>\n"
        "</table>"
    ),
    "bp.10.strategie_commerciale": (
        "Strategie d'acquisition et de developpement commercial : canaux "
        "d'acquisition actuels et envisages, politique de prix assumee, "
        "plan de visibilite (reseaux, partenariats, bouche-a-oreille), "
        "objectifs commerciaux par annee, logique de fidelisation."
    ),
    "bp.11.strategie_developpement": (
        "Trajectoire de developpement du projet : phasage strategique sur "
        "3 ans (structuration / croissance maitrisee / consolidation), "
        "jalons cles par phase, logique de montee en charge progressive. "
        "La strategie doit etre financable et operationnellement realiste."
    ),
    "bp.12.organisation_moyens": (
        "Organisation humaine et moyens materiels : role du dirigeant, "
        "equipe actuelle et recrutements envisages, moyens materiels "
        "existants et a acquerir, locaux et equipements, fournisseurs "
        "strategiques. Coherent avec le stade de developpement du projet."
    ),
    "bp.13.structure_juridique": (
        "Structure juridique et reglementaire : forme juridique retenue et "
        "justification, regime fiscal, statut social du dirigeant, "
        "contraintes reglementaires specifiques au secteur et a la zone, "
        "protection de la marque ou propriete intellectuelle si applicable."
    ),
    # `bp.14.besoin_financement` et `bp.15.previsionnel_tresorerie` ont ete
    # RETIRES : c'etaient les dispatchers des deux fusions de juillet 2026,
    # defaites le 05/08/2026 au retour aux vingt chapitres du document V1
    # FINALE. Les laisser aurait maintenu deux cles vers un chapitre qui
    # n'existe plus, et la prochaine relecture aurait cru le chapitre encore
    # fusionne.
    "bp.14.investissements": (
        "Investissements et besoins au demarrage : nature et montant des "
        "investissements initiaux, apports en nature eventuels, besoin en "
        "fonds de roulement, tresorerie de securite minimale requise. "
        "Chiffres argumentes et coherents avec l'activite."
    ),
    "bp.15.plan_financement": (
        "Plan de financement initial : synthese des besoins de demarrage, "
        "ressources mobilisees (apports propres, emprunt bancaire, "
        "subventions, investisseurs), equilibre du plan. "
        "Logique financiere transparente et defensable. "
        "Puis genere en HTML inline (sans <html>/<body>) un graphique barres "
        "de la repartition des ressources de financement (adapte les donnees "
        "reelles), sur ce pattern :\n"
        "<h3 style=\"font-size:14pt;margin:4mm 0 2mm\">Repartition des ressources "
        "de financement</h3>\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:3mm 0;"
        "font-size:9.5pt\">\n"
        "<tr><td style=\"padding:1.5mm 3mm;border-bottom:0.5pt solid #EFEAD8;"
        "width:35%\">Apport personnel</td>"
        "<td style=\"padding:1.5mm 2mm;width:55%\">"
        "<div style=\"background:#C9A227;height:5mm;width:40%;"
        "display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold;color:#1A1A1A;"
        "width:10%\">40 %</td></tr>\n"
        "</table>\n"
        "Une ligne par source de financement reelle du projet, legende courte "
        "en italique sous le tableau."
    ),
    # bp.16 decoupe en 2 sections pour eviter la troncature sur les tables
    # financieres + graphiques HTML (contenu > 3500 tokens en un seul appel).
    "bp.16.previsionnel_financier": (
        "Ce chapitre est genere en deux sections distinctes. "
        "Ne pas utiliser ce prompt directement."
    ),
    "bp.16.a.comptes_resultats": (
        "Compte de resultat previsionnel sur 3 ans (annee 1, 2, 3). "
        "Declare d'abord les hypotheses cles (prix moyen, volume, charges fixes/variables). "
        "Puis un tableau HTML detaille par annee : "
        "CA, Charges variables, Marge brute, Charges fixes, EBITDA, Amortissements, "
        "Resultat avant IS, IS estime, Resultat net. "
        "Calcule le seuil de rentabilite (point mort) et la capacite d'autofinancement. "
        "Scenario central obligatoire + analyse de sensibilite (+/-10% CA)."
    ),
    "bp.16.b.bilan_projection": (
        "1) GRAPHIQUE OBLIGATOIRE : bloc ```chart de type 'bar' avec title "
        "\"Evolution CA et EBITDA sur 3 ans\", labels [\"Annee 1\", \"Annee 2\", "
        "\"Annee 3\"], DEUX series (\"CA\" et \"EBITDA\") avec les valeurs "
        "reelles issues du compte de resultat previsionnel, unit \" k EUR\". "
        "2) Genere ensuite en HTML inline (sans <html>/<body>) : "
        "un bilan previsionnel simplifie annee 3 (actif / passif). "
        "3) Un tableau de financement du projet : apports propres, emprunts, aides. "
        "Conclure par une synthese 1 paragraphe sur la viabilite financiere globale."
    ),
    "bp.16.c.budget_tresorerie": (
        "Budget de tresorerie mensuel : logique de tresorerie sur 12-24 "
        "mois, integration de la saisonnalite, evolution du solde, "
        "securisation financiere. Fournis un tableau exploitable mois par mois. "
        "Puis genere en HTML inline (sans <html>/<body>) un graphique barres "
        "de l'evolution du solde de tresorerie sur 6 mois representatifs "
        "(incluant le point bas et le point haut de l'annee), meme pattern "
        "que les graphiques barres EVKHA (titre H3, tableau, barre #C9A227, "
        "valeurs reelles en euros, legende courte en italique)."
    ),
    "bp.17.risques_securisation": (
        "Risques identifies et facteurs de securisation : principaux risques "
        "(saisonnalite, dependance, concurrence, reglementation), leur "
        "probabilite et impact, leviers de securisation concrets pour chacun. "
        "Lecture lucide sans dramatisation."
    ),
    # Chapitre AJOUTE : aucun des vingt prompts precedents ne traitait la
    # remuneration du dirigeant. Le fichier `prompts/business_plan/
    # chapitre_18.md` porte la version complete ; cette entree existe pour les
    # appelants qui resolvent encore par cle.
    "bp.18.remuneration": (
        "Politique de remuneration du dirigeant et, le cas echeant, de "
        "l'equipe : montant prevu, calendrier, justification, impact sur la "
        "tresorerie, lien avec le statut social retenu. Charges sociales et "
        "leur poids dans le previsionnel. Arbitrage salaire/dividendes, "
        "maintien de l'ARE si applicable. Evolution progressive et conditions "
        "qui la declenchent. Une remuneration n'est credible que si son COUT "
        "COMPLET, charges comprises, figure dans le modele financier. Si le "
        "dirigeant ne se remunere pas au demarrage, presenter ce choix comme "
        "une securisation financiere, jamais comme une fragilite."
    ),
    "bp.19.conclusion": (
        "Conclusion strategique : synthese des points forts du projet, "
        "coherence economique et viabilite, adequation avec les objectifs "
        "du porteur, message final donnant confiance au lecteur. "
        "Ton positif et credible, pas commercial."
    ),
    "bp.20.annexes": (
        "Annexes : reponses explicites a chaque demande specifique du client "
        "(traitee / partiellement / non traitee + explication). "
        "Documents justificatifs et simulations complementaires si demandes."
    ),
    "bp.21.sources": (
        "Liste les sources utilisees pour construire ce business plan, "
        "regroupees par thematique (Donnees sectorielles, Reglementation, "
        "Financements et aides, Concurrence, Documents fournis par le porteur). "
        "Reprends en PRIORITE les URLs reelles du bloc SOURCES_WEB du contexte ; "
        "n'invente aucune URL absente de ce bloc. Format simple :\n"
        "## Donnees sectorielles\n- Nom - URL si disponible\n"
        "## Reglementation\n- ...\n"
        "Pas plus de 4-6 sources par thematique. Ajoute un court paragraphe "
        "'## Methodologie' (3-4 lignes) precisant la demarche (periode des "
        "donnees, hypotheses financieres assumees). Rester concis et structure."
    ),
}

# --- Strategie Business (STR) --------------------------------------------
# Prompts alignes avec la spec officielle EVKHA V1 (mai 2026).
# 17 chapitres analytiques + sources. Logique : diagnostic -> choix ->
# action. Objectif : aider un dirigeant a piloter avec une vision claire.

BUSINESS_STRATEGY_PROMPTS: dict[str, str] = {
    "str.00.fiche_projet": (
        "FORMAT STRICT (Bloc 5 Consignes EVKHA) : produis EXACTEMENT un tableau "
        "Markdown a 2 colonnes (Label | Valeur), AUCUN texte autour, AUCUNE "
        "introduction, AUCUN commentaire. Les 8 lignes obligatoires dans cet "
        "ordre exact :\n"
        "| Élément | Détail |\n"
        "|---|---|\n"
        "| Secteur | [valeur] |\n"
        "| Pays | [valeur] |\n"
        "| Projet | [description en 1-2 phrases] |\n"
        "| Zone | [valeur] |\n"
        "| Positionnement | [synthese 1 phrase] |\n"
        "| Clientèle cible | [synthese 1 phrase] |\n"
        "| Modèle économique | [synthese 1 phrase] |\n"
        "| Éléments à retenir | [3 a 5 points cles separes par ' / '] |\n"
        "Apres le tableau, saute une ligne et ajoute UNE SEULE section "
        "intitulee '## Questions auxquelles cette strategie repond' avec une "
        "liste a puces de 4 a 5 questions implicites du dirigeant orientees "
        "pilotage (type 'Quelles activites doivent devenir centrales et "
        "lesquelles abandonner ?'). Rien d'autre."
    ),
    "str.01.introduction": (
        "Introduction strategique generale : pose le cadre du document, "
        "explique pourquoi il existe et ce qu'il apportera concretement au "
        "dirigeant, distingue pilotage strategique et execution operationnelle. "
        "Transforme immediatement le livrable d'un rapport en outil de pilotage."
    ),
    "str.02.lecture_strategique": (
        "Lecture strategique du projet : analyse la situation reelle du "
        "business, son niveau de maturite, sa logique economique actuelle, "
        "ses enjeux de developpement. Produit un diagnostic de depart "
        "lucide qui sert de socle a tout le raisonnement strategique."
    ),
    "str.03.positionnement_actuel": (
        "Analyse du positionnement actuel : quelle place occupe reellement "
        "l'entreprise sur son marche, comment est-elle percue, coherence "
        "entre image / offre / cible / prix / ambition. Identifie les "
        "risques de dilution ou de confusion de positionnement. "
        "GRAPHIQUE OBLIGATOIRE : apres l'analyse redigee, insere un bloc "
        "```chart de type 'radar' avec title \"Positionnement du projet\", "
        "labels [\"Clarte de l'offre\", \"Notoriete\", \"Prix pergu\", "
        "\"Differenciation\", \"Coherence marque\", \"Digital\"], et une "
        "serie {\"name\": \"Aujourd'hui\", \"values\":[...]} avec des scores "
        "de 0 a 5 refletant l'etat REEL du business (pas ideal, pas projete). "
        "Si tu identifies un positionnement cible clair, ajoute une deuxieme "
        "serie {\"name\": \"Cible\", \"values\":[...]}. Le radar donne au "
        "dirigeant une lecture immediate des ecarts a combler."
    ),
    "str.04.forces_structurelles": (
        "Analyse des forces structurelles du business : identifie les "
        "veritables atouts internes (pas seulement des avantages de confort), "
        "evalue les ressources et avantages concurrentiels reels sur lesquels "
        "le developpement futur peut s'appuyer solidement. "
        "Puis genere en HTML inline (sans <html>/<body>) un encadre visuel "
        "listant les 4 a 5 forces principales avec un niveau de solidite "
        "(barre CSS), sur ce pattern (adapte au contenu reel) :\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:3mm 0;"
        "font-size:9.5pt\">\n"
        "<tr><td style=\"padding:1.5mm 3mm;border-bottom:0.5pt solid #EFEAD8;"
        "width:45%\">Force 1 : libelle concret</td>"
        "<td style=\"padding:1.5mm 2mm;width:45%\">"
        "<div style=\"background:#2E7D4F;height:5mm;width:80%;"
        "display:inline-block\"></div></td>"
        "<td style=\"padding:1.5mm 2mm;font-weight:bold;color:#1A1A1A;"
        "width:10%\">Solide</td></tr>\n"
        "</table>"
    ),
    "str.05.contraintes_fragilites": (
        "Analyse des contraintes et fragilites structurelles : identifie "
        "les vulnerabilites reelles du business, les risques structurels, "
        "les dependances critiques, les limites du modele actuel. "
        "Lecture lucide sans dramatisation ni complaisance. "
        "Puis genere en HTML inline (sans <html>/<body>) un encadre visuel "
        "listant les 4 a 5 fragilites principales avec un niveau de criticite "
        "(barre CSS), meme pattern que le graphique du chapitre precedent mais "
        "en couleur #B73E3E (rouge) au lieu de #2E7D4F, avec des niveaux "
        "Critique / Elevee / Moderee au lieu de Solide."
    ),
    "str.06.enjeux_positionnement": (
        "Enjeux strategiques du positionnement : demontre pourquoi la "
        "clarification du positionnement est un levier central, risques "
        "d'un positionnement flou, prepare la logique de specialisation "
        "et de differenciation structuree."
    ),
    "str.07.verticales_strategiques": (
        "Definition et priorisation des verticales strategiques : quelles "
        "activites doivent devenir centrales, lesquelles restent secondaires, "
        "lesquelles risquent de nuire a la coherence. Transforme un ensemble "
        "d'activites multiples en architecture strategique structuree."
    ),
    "str.08.valeur_differenciation": (
        "Proposition de valeur et differenciation : formalise la proposition "
        "de valeur du business, identifie les elements differenciants reels, "
        "clarifie pourquoi les clients doivent choisir cette entreprise. "
        "Transforme des qualites implicites en differenciation strategique assumee."
    ),
    "str.09.offres_actuelles": (
        "Lecture strategique des offres actuelles : analyse les offres "
        "existantes, evalue leur coherence avec le positionnement et la "
        "rentabilite, identifie les problemes de structuration commerciale "
        "ou de lisibilite pour les clients."
    ),
    "str.10.architecture_offre": (
        "Architecture d'offre cible : construit une structure d'offres "
        "coherente (niveaux de gamme, roles de chaque offre, parcours de "
        "valeur client), transforme une offre dispersee en architecture "
        "lisible et hierarchisee."
    ),
    "str.11.montee_gamme": (
        "Logique de montee en gamme et valeur percue : analyse comment "
        "mieux valoriser le business, structurer la montee en gamme, "
        "ameliorer la rentabilite sans necessairement trouver plus de clients. "
        "Propose des leviers concrets et actionnables."
    ),
    "str.12.canaux_acquisition": (
        "Analyse des canaux et acquisition actuelle : quels canaux "
        "l'entreprise utilise pour attirer des clients, leur coherence "
        "strategique, leur efficacite reelle, les desequilibres eventuels "
        "entre les differentes sources d'opportunites."
    ),
    "str.13.strategie_visibilite": (
        "Strategie de visibilite et acquisition coherente : construit une "
        "strategie d'acquisition alignee avec le positionnement, les offres "
        "et les verticales. Tous les canaux proposes sont justifies et "
        "connectes a la logique strategique globale."
    ),
    "str.14.rentabilite_modele": (
        "Lecture economique et rentabilite du modele : analyse la logique "
        "economique reelle, identifie les activites reellement rentables, "
        "evalue la soutenabilite financiere, comprend comment l'entreprise "
        "cree vraiment de la valeur. Va au-dela du simple chiffre d'affaires. "
        "Puis genere en HTML inline (sans <html>/<body>) un graphique barres "
        "comparant la rentabilite reelle des differentes activites ou offres "
        "du business (meme pattern que les graphiques barres EVKHA : titre "
        "H3, tableau, barre #C9A227 pour les activites rentables, barre "
        "#B73E3E pour celles qui ne le sont pas, valeurs reelles en % ou en "
        "euros, legende courte en italique)."
    ),
    "str.15.arbitrages_ressources": (
        "Arbitrages strategiques et allocation des ressources : quelles "
        "priorites retenir, quelles opportunites ecarter meme si elles "
        "generent du CA a court terme, comment allouer les ressources "
        "limitees de maniere coherente avec la vision."
    ),
    "str.16.pilotage_soutenabilite": (
        "Pilotage strategique et soutenabilite du business : comment "
        "l'entreprise peut se developper sans se fragiliser, sortir d'une "
        "logique purement reactive, indicateurs de pilotage a mettre en "
        "place, conditions de la soutenabilite humaine et financiere."
    ),
    "str.17.feuille_route": (
        "Feuille de route strategique et priorisation : actions prioritaires "
        "a court terme (0-3 mois), orientations a moyen terme (3-12 mois), "
        "cap a long terme (1-3 ans). Pour chaque action : quoi faire, "
        "pourquoi, quel indicateur prouvera le succes. "
        "Avant le detail textuel, genere une frise chronologique visuelle en "
        "HTML inline (sans <html>/<body>) avec 3 blocs colores cote a cote, "
        "sur ce pattern (remplace les exemples par les actions reelles, 2 a 3 "
        "actions cle par bloc) :\n"
        "<table style=\"border-collapse:collapse;width:100%;margin:4mm 0;"
        "font-size:9pt;table-layout:fixed\">\n"
        "<tr>"
        "<th style=\"background:#C9A227;color:#1A1A1A;padding:2mm;"
        "text-align:center;border:0.5pt solid #EFEAD8\">Court terme "
        "(0-3 mois)</th>"
        "<th style=\"background:#1A1A1A;color:#fff;padding:2mm;"
        "text-align:center;border:0.5pt solid #EFEAD8\">Moyen terme "
        "(3-12 mois)</th>"
        "<th style=\"background:#2E7D4F;color:#fff;padding:2mm;"
        "text-align:center;border:0.5pt solid #EFEAD8\">Long terme "
        "(1-3 ans)</th>"
        "</tr>\n"
        "<tr>"
        "<td style=\"vertical-align:top;padding:2mm;border:0.5pt solid "
        "#EFEAD8;background:#FBF8EF\"><ul><li>Action 1</li><li>Action 2</li>"
        "</ul></td>"
        "<td style=\"vertical-align:top;padding:2mm;border:0.5pt solid "
        "#EFEAD8;background:#FBF8EF\"><ul><li>Action 1</li><li>Action 2</li>"
        "</ul></td>"
        "<td style=\"vertical-align:top;padding:2mm;border:0.5pt solid "
        "#EFEAD8;background:#FBF8EF\"><ul><li>Action 1</li><li>Action 2</li>"
        "</ul></td>"
        "</tr>\n"
        "</table>"
    ),
    "str.18.annexe_brief": (
        "Annexe finale (format identique aux annexes EM) : pour chaque demande "
        "specifique du brief client, fournis une reponse synthetique de 1-2 "
        "paragraphes suivie d'un encadre intitule 'Strategie bonus' contenant "
        "2-3 pistes operationnelles concretes. Numerotation A.1, A.2, A.3... "
        "Ton plus direct que les chapitres : conversation finale avec le "
        "dirigeant."
    ),
    "str.19.sources": (
        "Liste les sources utilisees pour construire cette strategie, "
        "regroupees par thematique (Donnees marche, Benchmarks sectoriels, "
        "Reglementation, Documents client). Reprends en PRIORITE les URLs "
        "reelles du bloc SOURCES_WEB du contexte ; n'invente aucune URL absente "
        "de ce bloc. Format simple :\n"
        "## Donnees marche\n- Nom - URL si disponible\n"
        "## Benchmarks sectoriels\n- ...\n"
        "Pas plus de 4-6 sources par thematique. Ajoute un court paragraphe "
        "'## Methodologie' (3-4 lignes) precisant la demarche (croisement "
        "diagnostic / arbitrages / feuille de route). Rester concis et structure."
    ),
}


def prompt_instruction(prompt_key: str) -> str:
    """Renvoie l'instruction chapitre, ou une consigne generique de repli."""
    return (
        MARKET_STUDY_PROMPTS.get(prompt_key)
        or COMPETITOR_STUDY_PROMPTS.get(prompt_key)
        or BUSINESS_PLAN_PROMPTS.get(prompt_key)
        or BUSINESS_STRATEGY_PROMPTS.get(prompt_key)
        or (
            "Redige ce chapitre selon la methode EVKHA : donnees chiffrees, "
            "sourcees, concretes et exploitables, ton mentor."
        )
    )
