# Generated by Django 5.2.14 on 2026-06-01 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCredentialRef',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('google', 'Google Docs / Drive'), ('gamma', 'Gamma'), ('brevo', 'Brevo'), ('systeme', 'Systeme.io'), ('tally', 'Tally'), ('n8n', 'n8n')], max_length=24)),
                ('env_var_name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['provider', 'env_var_name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'env_var_name'), name='uniq_credential_ref_provider_env')],
            },
        ),
    ]
