# Generated by Django 5.2.14 on 2026-06-01 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('google', 'Google Docs / Drive'), ('gamma', 'Gamma'), ('brevo', 'Brevo'), ('systeme', 'Systeme.io'), ('tally', 'Tally'), ('n8n', 'n8n')], max_length=24)),
                ('event_id', models.CharField(max_length=160)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Recue'), ('accepted', 'Acceptee'), ('duplicate', 'Doublon'), ('rejected', 'Rejetee'), ('failed', 'Echec')], default='received', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_webhook_event_provider_event')],
            },
        ),
    ]
