# Generated by Django 5.2.14 on 2026-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_webhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('received', 'Recue'), ('accepted', 'Acceptee'), ('processed', 'Traitee'), ('duplicate', 'Doublon'), ('rejected', 'Rejetee'), ('failed', 'Echec')], default='received', max_length=16),
        ),
    ]
