# Generated by Django 5.2.14 on 2026-07-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_provider_choices_systeme_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('received', 'Recue'), ('accepted', 'Acceptee'), ('processed', 'Traitee'), ('duplicate', 'Doublon'), ('rejected', 'Rejetee'), ('failed', 'Echec'), ('skipped', 'Ignoree (produit non-EVKHA)')], default='received', max_length=16),
        ),
    ]
