# Generated by Django 5.2.16 on 2026-08-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_webhookevent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcredentialref',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('google', 'Google Docs / Drive'), ('gamma', 'Gamma'), ('brevo', 'Brevo'), ('systeme', 'Systeme.io (commandes)'), ('systeme_sub', 'Systeme.io (abonnements)'), ('tally', 'Tally'), ('n8n', 'n8n'), ('stripe', 'Stripe (abonnements)')], max_length=24),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('google', 'Google Docs / Drive'), ('gamma', 'Gamma'), ('brevo', 'Brevo'), ('systeme', 'Systeme.io (commandes)'), ('systeme_sub', 'Systeme.io (abonnements)'), ('tally', 'Tally'), ('n8n', 'n8n'), ('stripe', 'Stripe (abonnements)')], max_length=24),
        ),
    ]
