# Generated by Django 5.2.14 on 2026-06-01 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('customer_type', models.CharField(choices=[('b2c', 'B2C'), ('b2b', 'B2B')], default='b2c', max_length=8)),
                ('systeme_contact_id', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
