# Generated by Django 5.2.16 on 2026-07-29 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=140)),
                ('code', models.SlugField(unique=True)),
                ('credits_par_echeance', models.PositiveSmallIntegerField(default=0)),
                ('prix_mensuel_cents', models.PositiveIntegerField(default=0)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('report_credits', models.CharField(choices=[('aucun', 'Aucun report'), ('integral', 'Report intégral'), ('plafonne', 'Report plafonné')], default='aucun', max_length=12)),
                ('plafond_report', models.PositiveSmallIntegerField(default=0)),
                ('regenerations_offertes', models.PositiveSmallIntegerField(default=1)),
                ('validation_socle_par_client', models.BooleanField(default=False)),
                ('controle_qualite_avant_envoi', models.BooleanField(default=False)),
                ('reference_paiement', models.CharField(blank=True, max_length=160)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'formule',
                'verbose_name_plural': 'formules',
                'ordering': ['prix_mensuel_cents', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raison_sociale', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue')], default='active', max_length=12)),
                ('marque_blanche', models.BooleanField(default=True)),
                ('validation_socle_par_client', models.BooleanField(default=False)),
                ('controle_qualite_avant_envoi', models.BooleanField(default=False)),
                ('seuil_alerte_credits', models.PositiveSmallIntegerField(default=1)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organisations', to='customers.customer')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='PortefeuilleCredits',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portefeuille', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'portefeuille de crédits',
                'verbose_name_plural': 'portefeuilles de crédits',
            },
        ),
        migrations.CreateModel(
            name='MembreOrganisation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('membre', 'Membre'), ('lecture', 'Lecture seule')], default='membre', max_length=16)),
                ('invite_le', models.DateTimeField(blank=True, null=True)),
                ('revoque_le', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances', to='customers.customer')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='organisations.organisation')),
            ],
            options={
                'verbose_name': "membre d'organisation",
                'verbose_name_plural': "membres d'organisation",
                'ordering': ['organisation', 'customer'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'customer'), name='uniq_membre_par_organisation')],
            },
        ),
        migrations.CreateModel(
            name='ClientFinal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raison_sociale', models.CharField(max_length=200)),
                ('secteur', models.CharField(blank=True, max_length=200)),
                ('pays', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('logo_url', models.URLField(blank=True)),
                ('couleur_principale', models.CharField(blank=True, max_length=7)),
                ('couleur_secondaire', models.CharField(blank=True, max_length=7)),
                ('couleur_fond', models.CharField(blank=True, max_length=7)),
                ('mention_confidentialite', models.CharField(blank=True, max_length=200)),
                ('archive_le', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_finaux', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'client final',
                'verbose_name_plural': 'clients finaux',
                'ordering': ['raison_sociale'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'raison_sociale'), name='uniq_client_final_par_organisation')],
            },
        ),
        migrations.CreateModel(
            name='AbonnementOrganisation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('resilie', 'Résilié')], default='actif', max_length=12)),
                ('debut_le', models.DateTimeField()),
                ('fin_le', models.DateTimeField(blank=True, null=True)),
                ('derniere_periode_dotee', models.CharField(blank=True, db_index=True, max_length=7)),
                ('reference_paiement', models.CharField(blank=True, max_length=160)),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='organisations.formule')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ['-debut_le'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'actif')), fields=('organisation',), name='uniq_abonnement_actif_par_organisation')],
            },
        ),
        migrations.CreateModel(
            name='MouvementCredit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('dotation', "Dotation d'abonnement"), ('achat', 'Achat de crédits additionnels'), ('geste', 'Geste commercial'), ('debit', 'Débit pour une génération'), ('remboursement', 'Remboursement sur échec'), ('expiration', 'Expiration en fin de période')], max_length=16)),
                ('quantite', models.IntegerField()),
                ('motif', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=140)),
                ('auteur', models.CharField(blank=True, max_length=200)),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='organisations.portefeuillecredits')),
            ],
            options={
                'verbose_name': 'mouvement de crédit',
                'verbose_name_plural': 'mouvements de crédit',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite', 0), _negated=True), name='mouvement_credit_non_nul'), models.UniqueConstraint(condition=models.Q(('type__in', ['debit', 'remboursement'])), fields=('portefeuille', 'type', 'reference'), name='uniq_mouvement_par_reference')],
            },
        ),
    ]
