# Generated by Django 5.2.16 on 2026-07-29 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_subscription'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteClient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actif', models.BooleanField(default=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte', to='customers.customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'compte client',
                'verbose_name_plural': 'comptes client',
            },
        ),
        migrations.CreateModel(
            name='JetonAcces',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condensat', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expire_le', models.DateTimeField()),
                ('revoque_le', models.DateTimeField(blank=True, null=True)),
                ('derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jetons', to='organisations.compteclient')),
            ],
            options={
                'verbose_name': "jeton d'accès",
                'verbose_name_plural': "jetons d'accès",
                'ordering': ['-created_at'],
            },
        ),
    ]
