# Generated by Django 5.2.16 on 2026-07-29 22:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_subscription'),
        ('organisations', '0002_compteclient_jetonacces'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCommerciale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('changement_formule', 'Changement de formule'), ('credits_additionnels', 'Achat de crédits additionnels'), ('resiliation', 'Résiliation')], max_length=24)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('traitee', 'Traitée'), ('refusee', 'Refusée')], default='ouverte', max_length=12)),
                ('quantite', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('traitee_le', models.DateTimeField(blank=True, null=True)),
                ('reponse', models.TextField(blank=True)),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='customers.customer')),
                ('formule_visee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='organisations.formule')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'demande commerciale',
                'verbose_name_plural': 'demandes commerciales',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'ouverte')), fields=('organisation', 'type'), name='uniq_demande_ouverte_par_type')],
            },
        ),
    ]
