# Generated by Django 5.2.16 on 2026-07-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_demandecommerciale'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='couleur_fond',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='organisation',
            name='couleur_principale',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='organisation',
            name='couleur_secondaire',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='mention_confidentialite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pays',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organisation',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organisation',
            name='secteur',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organisation',
            name='ville',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
