# Generated by Django 5.2.16 on 2026-07-30 08:28

import django.db.models.deletion
import organisations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_subscription'),
        ('orders', '0004_order_organisation'),
        ('organisations', '0004_organisation_couleur_fond_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('logo', 'Logo'), ('document', 'Document complémentaire')], default='document', max_length=12)),
                ('fichier', models.FileField(upload_to=organisations.models._chemin_piece_jointe)),
                ('nom_original', models.CharField(max_length=200)),
                ('type_mime', models.CharField(blank=True, max_length=120)),
                ('taille_octets', models.PositiveIntegerField(default=0)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='orders.order')),
                ('depose_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_deposees', to='customers.customer')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
                'ordering': ['-created_at'],
            },
        ),
    ]
