# Generated by Django 5.2.16 on 2026-07-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_piecejointe'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='avantages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='formule',
            name='mise_en_avant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formule',
            name='prix_credit_supplementaire_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formule',
            name='rang',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
