# Generated by Django 5.2.16 on 2026-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_tarifs_publics'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementorganisation',
            name='fin_de_periode_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abonnementorganisation',
            name='renouvellement_actif',
            field=models.BooleanField(default=True),
        ),
    ]
