# Generated by Django 5.2.16 on 2026-08-07 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_rattrapage_donnees_des_formules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formule_code', models.CharField(blank=True, max_length=64)),
                ('montant_cents', models.PositiveIntegerField()),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('reference_facture', models.CharField(max_length=160, unique=True)),
                ('reference_abonnement', models.CharField(blank=True, max_length=160)),
                ('paye_le', models.DateTimeField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaissements', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'encaissement',
                'verbose_name_plural': 'encaissements',
                'ordering': ['-paye_le'],
                'indexes': [models.Index(fields=['paye_le'], name='organisatio_paye_le_1bea88_idx')],
            },
        ),
    ]
