# Generated by Django 5.2.16 on 2026-08-07 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_encaissements'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='formule_pressentie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisations.formule'),
        ),
    ]
