# Generated by Django 5.2.16 on 2026-08-07 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_formule_pressentie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativePaiement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objet', models.CharField(choices=[('abonnement', 'Souscription à une formule'), ('credits', 'Achat de crédits supplémentaires')], max_length=16)),
                ('etat', models.CharField(choices=[('ouverte', 'Ouverte — en attente de paiement'), ('payee', 'Payée'), ('abandonnee', 'Abandonnée')], default='ouverte', max_length=16)),
                ('quantite', models.PositiveSmallIntegerField(default=0)),
                ('montant_cents', models.PositiveIntegerField(default=0)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('reference_session', models.CharField(max_length=200, unique=True)),
                ('payee_le', models.DateTimeField(blank=True, null=True)),
                ('relancee_le', models.DateTimeField(blank=True, null=True)),
                ('relances', models.PositiveSmallIntegerField(default=0)),
                ('formule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisations.formule')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_paiement', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'tentative de paiement',
                'verbose_name_plural': 'tentatives de paiement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['etat', '-created_at'], name='organisatio_etat_94cc0e_idx')],
            },
        ),
    ]
