# Generated by Django 5.2.16 on 2026-08-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_tentatives_de_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='type_de_compte',
            field=models.CharField(choices=[('abonne', 'Abonné'), ('a_l_unite', "À l'unité")], default='abonne', max_length=12),
        ),
    ]
