# Generated by Django 5.2.16 on 2026-08-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_organisation_type_de_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativepaiement',
            name='objet',
            field=models.CharField(choices=[('abonnement', 'Souscription à une formule'), ('credits', 'Achat de crédits supplémentaires'), ('livrable', "Achat d'une étude à l'unité")], max_length=16),
        ),
    ]
