# Generated by Django 5.2.16 on 2026-08-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_alter_tentativepaiement_objet'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcredit',
            name='livrable',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
