# Generated by Django 5.2.16 on 2026-08-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_produitboutique_extrait_and_more'),
        ('organisations', '0014_mouvementcredit_livrable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativepaiement',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tentativepaiement',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentatives', to='catalog.produitboutique'),
        ),
        migrations.AlterField(
            model_name='tentativepaiement',
            name='objet',
            field=models.CharField(choices=[('abonnement', 'Souscription à une formule'), ('credits', 'Achat de crédits supplémentaires'), ('livrable', "Achat d'une étude à l'unité"), ('produit', "Achat d'une étude en boutique")], max_length=16),
        ),
        migrations.AlterField(
            model_name='tentativepaiement',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_paiement', to='organisations.organisation'),
        ),
    ]
