# Generated by Django 5.2.16 on 2026-08-22 15:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0015_tentativepaiement_email_tentativepaiement_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('lien_libelle', models.CharField(blank=True, max_length=60)),
                ('lien_cible', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée')], default='brouillon', max_length=20)),
                ('envoyee_le', models.DateTimeField(blank=True, null=True)),
                ('courriels_envoyes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnonceVue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='organisations.annonce')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces_vues', to='organisations.membreorganisation')),
            ],
            options={
                'verbose_name': 'annonce vue',
                'verbose_name_plural': 'annonces vues',
                'constraints': [models.UniqueConstraint(fields=('annonce', 'membre'), name='annonce_vue_unique_par_membre')],
            },
        ),
    ]
