# Generated by Django 5.2.16 on 2026-09-04 05:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_subscription'),
        ('generation', '0014_compteurs_de_cache_et_tentatives_perdues'),
        ('organisations', '0016_annonce_annoncevue'),
    ]

    operations = [
        migrations.AddField(
            model_name='jetonacces',
            name='assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jetonacces',
            name='ouvert_par',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sujet', models.CharField(choices=[('document', 'Un document produit ne va pas'), ('generation', 'Une génération a échoué ou reste bloquée'), ('facturation', 'Facturation, crédits ou abonnement'), ('acces', "Connexion ou accès à l'espace"), ('autre', 'Autre chose')], default='autre', max_length=16)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité')], default='nouveau', max_length=12)),
                ('reponse', models.TextField(blank=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='customers.customer')),
                ('livrable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='generation.generationjob')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut', '-created_at'], name='organisatio_statut_08d714_idx')],
            },
        ),
    ]
