# Generated by Django 5.2.14 on 2026-06-01 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('docx', 'Word'), ('pdf', 'PDF'), ('gamma_pdf', 'Gamma PDF'), ('gamma_pptx', 'Gamma PPTX'), ('link', 'Lien')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('ready', 'Pret'), ('expired', 'Expire'), ('failed', 'Echec')], default='pending', max_length=16)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('download_url', models.URLField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='generation.generationjob')),
            ],
            options={
                'ordering': ['job', 'kind', '-created_at'],
            },
        ),
    ]
